screwdriver-cd/data-schema

README.md

During the migration, we missed a few updates to the README

Readme correctly describes the module

---

index.js
lib/mutate.js
model/build.js
model/job.js
model/pagination.js
model/pipeline.js
model/platform.js
model/task.js
model/user.js
package.json
test/data/build.create.yaml
test/data/build.get.yaml
test/data/build.yaml
test/data/task.create.yaml
test/data/task.get.yaml
test/data/task.update.yaml
test/data/task.yaml
test/task.test.js

Migrated over from screwdriver-cd/data-model#16
@stjohnjohnson wrote:
Think of `tasks` like the children of the parent job.
Also removing `queuedReason`, renaming `slave` to `machine`, and adding `unique` property.

Adding Tasks

---

README.md
plugins/datastore.js
plugins/index.js
test/data/datastore.data.yaml
test/data/datastore.id.yaml
test/data/datastore.paginate.yaml
test/plugins/datastore.test.js

Adding validation for the datastore to use
Thanks @stjohnjohnson

Add validation for datastore

---

index.js

Expose plugins

---

models/user.js

Login is not working because validation failed. 
Token is currently not part of the user base so we need to add it.

Add token to user base

---

api/index.js
api/webhooks/build.js
api/webhooks/index.js
package.json
test/api/webhooks/build.test.js
test/data/webhooks.build.all.yaml
test/data/webhooks.build.status.yaml

This PR is adding in api validation for build webhooks. 
When a build has finished we want to update status and meta

Build Webhook Api Validation

---

models/build.js
models/job.js
models/pipeline.js
models/user.js
test/models/index.test.js

Since our models should be a representation of a database row, it sure would be nice to be able to get all the field names.

Add a property containing a list of all the keys in the model

---

models/build.js
test/data/build.yaml

Resolves https://github.com/screwdriver-cd/models/issues/37

Change sha1 to sha

---

screwdriver.yaml

Configuration enables `npm install` & `npm test`

Add Screwdriver build configuration

---

plugins/index.js
plugins/scm.js
test/data/scm.getCommitSha.yaml
test/data/scm.getPermissions.yaml
test/data/scm.updateCommitStatus.yaml
test/plugins/scm.test.js

This PR adds in better schema validation for the scm-base module
It depends on other values from throughout the models

Schema Validation for Scm-Base plugin

---

models/job.js
test/data/job.update.yaml
test/data/job.yaml

To support matrix later, containers need to be an array

Containers should be an array

---

plugins/scm.js
test/data/scm.getFile.yaml

This PR adds in schema for use in the `scm-base.getFile` function

Schema validation for getFile function

---

plugins/scm.js

Add something so we can set target_url.

optional url for commit status

---

api/validator.js
models/build.js
models/index.js
models/job.js
models/log.js
package.json
test/data/build.yaml
test/data/job.update.yaml
test/data/job.yaml
test/data/log.yaml
test/models/log.test.js

- Starting a new Log Lines model
- Adding step details to Build
- Adding Permutations to Job

Adding Log Lines, Step Details, and Permutations

---

models/build.js
test/data/build.yaml

Including:
- Who started the build (link to user info)
- Who authored the commit (link to user info)
- Commit message
- Link to Commit

Adding more commit information to Build

---

models/index.js
models/secret.js
package.json
test/data/secret.create.yaml
test/data/secret.get.yaml
test/data/secret.remove.yaml
test/data/secret.yaml
test/models/secret.test.js

Initial addition of secret schema.

Add secret model

---

api/validator.js

- Add secrets to SCHEMA_JOB_PERMUTATION in validator

Add secrets to validator

---

models/job.js
test/data/job.get.yaml

Currently breaking Screwdriver release as they conflict.

Removing isPR as it's a function in Models

---

models/job.js
package.json
test/data/job.yaml

We need the index so we can just get the list of active jobs.

Removing containers (not used anymore) and adding state as an index

---

models/pipeline.js
test/data/pipeline.get.yaml

Pipeline should have the latest state of the workflow stored.

Storing Workflow in Pipeline

---

package.json
plugins/scm.js
test/data/scm.getRepoId.yaml
test/plugins/scm.test.js

This PR adds an input validation for getRepoId screwdriver-cd/scm-base#5

Add new schema for input of getRepoId

---

plugins/scm.js
test/data/scm.updateCommitStatus.yaml

This let's us put multiple messages on a given commit.

[1] Adding optional jobName to updateStatus

---

models/pipeline.js
package.json

This PR changes the key for generating pipeline ID. 
screwdriver-cd/screwdriver#160

Change the key for pipeline to scmRepo.id

---

models/pipeline.js

- Revert @catto 's [change](https://github.com/screwdriver-cd/data-schema/commit/1d72e57df84311358452f34a83bc043db4981057) for now
- We are not ready for it yet

Revert catto's change for now

---

api/pagination.js
core/scm.js
models/build.js
models/job.js
models/pipeline.js
models/secret.js
models/user.js
plugins/datastore.js
plugins/executor.js
plugins/scm.js
test/api/loglines.test.js
test/api/pagination.test.js
test/api/validator.test.js
test/config/base.test.js
test/config/job.test.js
test/config/regex.test.js
test/config/workflow.test.js
test/core/scm.test.js
test/data/scm.decorateAuthor.yaml
test/models/build.test.js
test/models/index.test.js
test/models/job.test.js
test/models/pipeline.test.js
test/models/secret.test.js
test/models/user.test.js
test/plugins/datastore.test.js
test/plugins/executor.test.js
test/plugins/scm.test.js

- Remove scmUri from input of decorateAuthor
- Add newline after `use strict` for new eslint rule

remove scmUri from input of decorateAuthor

---

config/regex.js
test/config/regex.test.js

Fixing regex for `checkoutUrl` in favor of a better one
See St. John's comment here: https://github.com/screwdriver-cd/scm-bitbucket/pull/4

Fix checkoutUrl regex

---

config/regex.js
test/config/regex.test.js

- Change the scmUri regex to match any string as ID except for `:`

Change the scmUri regex to match any string

---

models/pipeline.js
plugins/scm.js
test/data/pipeline.update.yaml
test/data/pipeline.yaml
test/models/pipeline.test.js

- Remove the checkoutUrl from the pipeline MODEL
- Thus the checkoutUrl column will not be created when defining table

Seperate checkoutUrl from the pipeline model

---

plugins/scm.js
test/data/scm.updateCommitStatus.yaml

Relates to https://github.com/screwdriver-cd/screwdriver/issues/285

Make targetUrl for commit status required

---

models/event.js
models/index.js
package.json
test/data/event.create.yaml
test/data/event.get.full.yaml
test/data/event.get.yaml
test/data/event.yaml
test/models/event.test.js
test/models/index.test.js

Include the schema for the `event` model. 
Relates to https://github.com/screwdriver-cd/screwdriver/issues/221

[event-1] Define schema for event model

---

models/event.js
test/data/event.get.full.yaml
test/data/event.get.yaml
test/data/event.yaml
test/models/event.test.js

- Add event `type` to the table so that UI can filter by type
- Add `type` to index
- Add `createTime` to rangeKey to sort events by time
- Have `pr` and `pipeline` for now, will probably add more types later

Add type to event table

---

CHANGELOG.md
models/build.js
package.json
test/data/build.yaml

Adding commands and environment information to builds so that the launcher can use this information when running commands

Add commands and environment to steps in builds

---

CHANGELOG.md
models/build.js
package.json
test/models/index.test.js

- needed to sort the events
Related to https://github.com/screwdriver-cd/screwdriver/pull/355

Add event number as sort key for build

---

models/event.js
models/pipeline.js
models/user.js

I found the same issue as screwdriver-cd/screwdriver#325 on the latest version of Screwdriver.
I added length limitations for each key to fix it.

fix: Add length for mysql index

---

models/build.js

Added examples for Step fields. Resolves https://github.com/screwdriver-cd/screwdriver/issues/415

First day commit

---

api/validator.js
test/data/validator.input.yaml
test/data/validator.output.yaml

Fix to expose settings in validator to allow settings in screwdriver.yaml
related to https://github.com/screwdriver-cd/screwdriver/issues/465

fix: expose settings in validator

---

config/regex.js
test/config/job.test.js
test/data/config.job.template-with-label.good.yaml

Allow users to specify which label they want to pull. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/470

fix(470): allow label in template name

---

api/validator.js
config/job.js
models/build.js
test/data/config.job.steps.yaml
test/data/step.get.yaml
test/data/validator.output.yaml

Rollback all `alwaysRun` PRs.
https://github.com/screwdriver-cd/data-schema/pull/120
https://github.com/screwdriver-cd/data-schema/pull/119
Related to https://github.com/screwdriver-cd/screwdriver/issues/473

fix: rollback alwaysRun

---

api/validator.js

Pipeline is fixed now: Reverts screwdriver-cd/data-schema#123

Revert "fix: allow alwaysRun field for now to fix the pipeline"

---

models/build.js
test/data/build.update.yaml

Reverts screwdriver-cd/data-schema#127
Column for the new field was not created automatically. Will investigate later.

Revert "feat(545): Add a field for builds to know when to timeout"

---

package.json

Adding Min to authors in the package.json

fix: Add Min to package.json

---

models/build.js
test/data/build.update.yaml

Reverts screwdriver-cd/data-schema#142 since we are having trouble with sequelize 4.0

Revert "feat(545): add field to timeout builds"

---

api/validator.js
config/annotations.js
config/base.js
config/index.js
config/job.js
test/config/annotations.test.js
test/config/job.test.js
test/data/config.annotations.yaml
test/data/config.job.annotations.yaml

Annotations are a grouping of key-value pairs and can be either pipeline- or job-level specifications.
More details available at: screwdriver-cd/screwdriver#580

feat(580): support for annotations

---

config/job.js
test/config/job.test.js
test/data/config.job.description.yaml

- Add a schema for description
- Add a test data file (config.job.description.yaml)
- Add a test to validate description

feat(423): Allow descriptions in yaml file

---

api/validator.js
config/job.js
test/data/validator.input.yaml
test/data/validator.output.yaml

- Add SCHEMA_DESCRIPTION to SCHEMA_JOB_PERMUTATION and SCHEMA_OUTPUT
- Modify validator.input.yaml and validator.output.yaml to make sure
description and annotations work (related to annotations PR https://github.com/screwdriver-cd/data-schema/pull/145).
Part of #149

fix(423): Add job descriptions to validator

---

test/data/templatetag.remove.yaml
test/models/templatetag.test.js

Forgot to add tests for https://github.com/screwdriver-cd/data-schema/pull/158

fix(616): Add tests for template tag remove schema

---

models/pipeline.js
models/user.js
package.json
test/data/collection.get.yaml
test/data/pipeline.get.yaml
test/data/pipeline.yaml
test/data/user.create.yaml
test/data/user.yaml

Reverts screwdriver-cd/data-schema#160
We're going to complete implementing the multiple scms feature. screwdriver-cd/screwdriver#365
This PR is the first one you can start merging. I'll let you know when it is ready to review and merge.
Added `scmContext` key to test data for collection due to schema changes.

[DNMy] feat(365) - 1: Add scmContext to models #152

---

README.md

fix to make semantic-release happy

fix: link Screwdriver repo

---

models/collection.js
models/pipeline.js
test/data/collection.get.yaml
test/data/pipeline.get.yaml

Reverts screwdriver-cd/data-schema#174
Didn't bump major like we expected. 😢

fix: Revert "feat(collections): Add lastBuilds to pipeline. BREAKING CHANGE"

---

models/collection.js
models/pipeline.js
test/data/collection.get.yaml
test/data/pipeline.get.yaml

BREAKING CHANGE: Reverts screwdriver-cd/data-schema#175

feat(collections): Revert "fix: Revert "feat(collections): Add lastBuilds to pipeline. BREAKING CHANGE""

---

api/validator.js
config/job.js
config/regex.js
package.json
test/api/validator.test.js
test/config/job.test.js
test/data/config.job.jobv2.bad.yaml
test/data/config.job.jobv2.yaml
test/data/validator-with-requires.input.yaml
test/data/validator-with-requires.output.yaml

Allows the keyword `requires`
Related: https://github.com/screwdriver-cd/screwdriver/issues/723

feat(723): allows requires keyword for jobs

---

models/index.js
models/secret.js
models/trigger.js
test/data/trigger.yaml
test/models/trigger.test.js

Add schema for the new trigger table.
No endpoint should be exposed to the users.
Related: https://github.com/screwdriver-cd/screwdriver/issues/770

feat(770): Add schema for trigger table

---

models/build.js
test/data/build.update.yaml

add a optional statusMessage field to build model
Related to https://github.com/screwdriver-cd/screwdriver/issues/694

feat(694): add an optional statusMessage field to build model

---

.gitignore
models/event.js
package-lock.json
package.json
test/data/event.get.full.yaml

Related to https://github.com/screwdriver-cd/screwdriver/issues/904

fix: Add event meta

---

core/scm.js
models/event.js
plugins/scm.js

adding verfication for PR field in event object
Related to https://github.com/screwdriver-cd/screwdriver/issues/822

make Joi for PR key in event object

---

models/banner.js

This is the same issue as #102 , #114 and #192 .
I added max length to 'type' in banner.js.

fix: Add key length for mysql

---

config/job.js
config/regex.js
test/data/template.yaml

Allow multiple images to be specified within a template.  
* Issue: https://github.com/screwdriver-cd/screwdriver/issues/1040

feat(1040): allow multiple images within a template

---

models/token.js
test/data/token.invalid.yaml
test/data/token.pipeline.yaml
test/models/token.test.js

Reverts screwdriver-cd/data-schema#250
This changes seem break backward compatibilitty. https://github.com/screwdriver-cd/models/pull/261#issuecomment-395230384

Revert "feat(614): [1] add pipelineId to token model"

---

config/job.js
config/regex.js
test/config/regex.test.js
test/data/config.job.jobv2.yaml

The branch specific trigger for `~pr` is not implemented yet.
* Fix branch filtering regex for pr trigger
* [workflow design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/workflow.md#branch-filtering-scm-branch-specific-jobs)
* issue https://github.com/screwdriver-cd/screwdriver/issues/1082

feat(1082): [12] [small] fix branch filtering regex for pr trigger

---

models/step.js

There is same issue as screwdriver-cd/screwdriver#325 on latest version of Screwdriver.
I added length limitation.

fix: [small] add key length for mysql

---

.gitignore
models/build.js
models/buildCluster.js
models/index.js
package.json
test/data/buildCluster.create.full.yaml
test/data/buildCluster.create.yaml
test/data/buildCluster.get.yaml
test/data/buildCluster.update.yaml
test/data/buildCluster.yaml
test/models/buildCluster.test.js

- Add build cluster model
- Add buildClusterName to build
Related to https://github.com/screwdriver-cd/screwdriver/issues/1319

fix(1319): add build cluster model

---

models/command.js
models/template.js
plugins/datastore.js
test/data/datastore.groupBy.yaml
test/data/template.compact.yaml
test/models/template.test.js
test/plugins/datastore.test.js

extending query options to datastore
related to: https://github.com/screwdriver-cd/screwdriver/issues/1271

feat(1271): extend query options

---

core/scm.js
models/job.js

added more info the PR and PR job
related: https://github.com/screwdriver-cd/screwdriver/issues/1419

feat(1419): extend job schema for pr job info

---

core/scm.js
models/job.js

related: https://github.com/screwdriver-cd/screwdriver/issues/1419
related: https://github.com/screwdriver-cd/ui/pull/395

fix: more pr & author info

---

models/build.js
package.json

reference: https://github.com/screwdriver-cd/screwdriver/issues/1412

feat(1412): build metrics

---

models/build.js

- add COLLAPSED and FROZEN build status
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1482
https://github.com/screwdriver-cd/screwdriver/issues/675

fix: add COLLAPSED and FROZEN build status

---

models/event.js
plugins/scm.js
test/data/scm.getChangedFilesInput.yaml

other PR: https://github.com/screwdriver-cd/scm-github/pull/126
related: https://github.com/screwdriver-cd/screwdriver/issues/1528

fix: add prNum and scm to event schema

---

core/scm.js
test/core/scm.test.js
test/data/scm.pr.yaml

In order to pass the validation, we need to add `ref` to the `SCHEMA_PR`
Issue:
https://github.com/screwdriver-cd/screwdriver/issues/1010#issuecomment-478911280
Other PRs:
[2] models: https://github.com/screwdriver-cd/models/pull/359
[3] api: https://github.com/screwdriver-cd/screwdriver/pull/1580

fix(1010): [1] add ref to scm.core.pr

---

config/regex.js
test/config/regex.test.js

Permit dot for sd-cmd version.
https://github.com/screwdriver-cd/screwdriver/issues/1505

fix(1505): permit dot sd-cmd

---

plugins/executor.js
test/data/executor.start.yaml

Related: https://github.com/screwdriver-cd/screwdriver/issues/1757

fix: allow state & archived [1]

---

api/validator.js
config/base.js
config/index.js
config/parameters.js
migrations/20191004-add_parameters_as_mediumtext-pipelines.js
models/pipeline.js
test/config/parameters.test.js
test/data/config.parameters.yaml

This PR is successor of https://github.com/screwdriver-cd/data-schema/pull/349
which add `parameters` on top level of `screwdriver.yaml`
Add `parameters` on top level of `screwdriver.yaml`
See `screwdriver.yaml` as example in here
https://github.com/adong/screwdriver-parameters-top-build/blob/604d2bbb7293a60cddef625a4c0e516d5e260099/screwdriver.yaml#L4
POST
GET

fix: add parameters to top level of screwdriver.yaml

---

api/loglines.js

Because sd-local needs `stepName` for output logs, we add `stepName` to logs of `log-service`.
- Add stepName to LogLines
https://github.com/screwdriver-cd/screwdriver/issues/1314

feat(1314): [1] Add stepName to loglines

---

config/regex.js
models/build.js

currently build schema rejects pr job name due to incorrect regex
fix regex so pr job name pass
https://github.com/screwdriver-cd/screwdriver/issues/1973

fix(1973): build schema incorrectly rejects pr job

---

plugins/executor.js

We need token to make api calls to the queue service and schema needs to allow passing to executor
This PR allows token to be passed to executor to make api calls
https://github.com/screwdriver-cd/screwdriver/issues/1951

feat(1951): Update Schema for executor

---

config/job.js
test/config/job.test.js
test/data/config.job.cache.bad.yaml
test/data/config.job.cache.yaml

Add cache property to job config.
screwdriver-cd/screwdriver#1748

feat(1748): [1] Add cache property to job config

---

plugins/scm.js
test/data/scm.openPr.yaml
test/plugins/scm.test.js

Adding a new method `openPr` in scm plugin
Add validation for `openPr` method in scm plugin
https://github.com/screwdriver-cd/scm-base/pull/77
https://github.com/screwdriver-cd/screwdriver/issues/1922

feat(1922): Add openPr property

---

config/parameters.js
test/data/config.parameters.yaml

For users can choose some values in parameters, multiple parameters are allowed in pipeline data-schema.
Multiple parameters are allowed in pipeline data-schema.
screwdriver-cd/screwdriver#2092

[1] feat(2092): Allow multiple default parameters

---

api/auth.js
models/pipeline.js
plugins/scm.js
test/data/auth.contexts.yaml
test/data/pipeline.create.yaml
test/data/scm.addDeployKey.yaml
test/plugins/scm.test.js

Fixes screwdriver-cd/screwdriver#1079
This PR adds relevant fields in the schemas for handling autoDeployKeyGeneration flag.
screwdriver-cd/screwdriver#1079

feat(1079): Validation schemas for deploy key pipeline [1]

---

api/validator.js
config/base.js
config/regex.js
migrations/20200922-add_column_subscribedConfigSha_to_builds.js
migrations/20200922-add_column_subscribedScmUrlsWithActions_to_pipelines.js
models/build.js
models/pipeline.js
plugins/scm.js
test/data/pipeline.get.yaml
test/data/scm.addWebhook.yaml

Fixes screwdriver-cd/screwdriver#1415
This PR adds items to the data-schema for handling new config and updated functions for external repo notifications
screwdriver-cd/screwdriver#1415

feat(1415): Add items to data schema for external repo validation

---

api/loglines.js
test/api/loglines.test.js
test/data/loglines.output.string.yaml
test/data/loglines.query.yaml

add schema change for log api
add schema change for log api
https://github.com/screwdriver-cd/screwdriver/pull/2200

fix(2068): Large step logs causes browser to hang

---

config/annotations.js

Add feature of https://github.com/screwdriver-cd/screwdriver/issues/2053
https://github.com/screwdriver-cd/screwdriver/issues/2053
[1] https://github.com/screwdriver-cd/data-schema/pull/414 (this PR)
[2] https://github.com/screwdriver-cd/config-parser/pull/111
UI: https://github.com/screwdriver-cd/ui/pull/605

fix(2053): [1] add RESERVED_JOB_ANNOTATIONS and RESERVED_PIPELINE_ANNOTATIONS

---

config/annotations.js

Add annotations for screwdriver-cd/screwdriver#2174
screwdriver-cd/screwdriver#2174
config-parser: https://github.com/screwdriver-cd/config-parser/pull/113

feat(2174): [1] Add annotations for mergeStep

---

models/build.js
plugins/index.js
plugins/notifications.js
test/data/notifications.schemaBuildData.yaml
test/plugins/notifications.test.js

The same definitions exist for both [notification-email](https://github.com/screwdriver-cd/notifications-email/blob/e9906f2601e50cddaf21e80b877992d01332ac34/index.js#L54-L62) and [notification-slack](https://github.com/screwdriver-cd/notifications-slack/blob/59f18306297795c4288591f562a552396ccacd72/index.js#L66-L74), and it is possible that the next time we add a feature, we will miss a fix for one or the other.
The definitions that exist in both [notification-email](https://github.com/screwdriver-cd/notifications-email/blob/e9906f2601e50cddaf21e80b877992d01332ac34/index.js#L54-L62) and [notification-slack](https://github.com/screwdriver-cd/notifications-slack/blob/59f18306297795c4288591f562a552396ccacd72/index.js#L66-L74) are combined in one place.
[1] …

[1] feat: add plugins/notifications

---

config/annotations.js

https://github.com/screwdriver-cd/screwdriver/issues/2273
Fix this point below:
> 1. Validator complains that it's not a valid job level annotation
Validator treat `displayName` as valid.
https://github.com/screwdriver-cd/screwdriver/issues/2273

fix(2273): treat displayName as valid

---

migrations/20210122-add_column_latestVersion_to_commands.js
migrations/20210122-add_column_latestVersion_to_templates.js
models/command.js
models/template.js
test/data/command.get.yaml
test/data/template.get.yaml

currently it's very slow to fetch/query all unique template/command
add a column to label latest version template/command for faster query
https://github.com/screwdriver-cd/screwdriver/issues/2312

fix(2312): add latest to template and command. BREAKING CHANGE: new field that need backfill

---

migrations/20210122-add_column_latestVersion_to_commands.js
migrations/20210122-add_column_latestVersion_to_templates.js

migration script breaks when table name contains special characters
wrap table name around double quotes

fix: wrap table name around double quote

---

migrations/20210122-add_column_latestVersion_to_commands.js
migrations/20210122-add_column_latestVersion_to_templates.js

fix: correct migration file. add transaction

---

migrations/20210310-add_uniquekey_to_builds.js
models/build.js

multiple build could be created for same job in same event
add unique constraint so only one build could be created for same job in same event
https://github.com/screwdriver-cd/screwdriver/issues/2071

fix(2071): add unique constraint to build

---

migrations/20210310-add_uniquekey_to_builds.js

supply fields in options instead
supply fields in options instead

fix: fix migration script

---

core/scm.js
test/data/pipeline.get.yaml
test/data/scm.repo.yaml

We need a field to indicate whether or not a pipeline is private
Add private field to pipeline model
https://github.com/screwdriver-cd/screwdriver/issues/466

feat(466): add private field to pipeline model

---

config/settings.js
test/data/pipeline.update.yaml

adding public property to pipeline setting
adding public property to pipeline setting
https://github.com/screwdriver-cd/screwdriver/issues/466

fix(466): add public to pipeline settings

---

plugins/executor.js

Executor needs a verify method to check for pod health
This PR adds verify function params schema 
https://github.com/screwdriver-cd/screwdriver/issues/2491

feat: add executor verify schema

---

plugins/executor.js

Update the executor schema obj as copying the object does not copy the validate prop
This PR updated the executor schema obj

feat: update executor schema obj

---

config/job.js
test/config/job.test.js
test/data/config.job.parameters.yaml

Schema to support job level parameters
https://github.com/screwdriver-cd/screwdriver/issues/2346

feat(2346): Job level parameters

---

api/validator.js
config/base.js
config/job.js
config/parameters.js
models/pipeline.js
test/config/job.test.js
test/data/config.job.parameters.yaml

Ability to define parameters at job level
Schema to support job level parameters
https://github.com/screwdriver-cd/screwdriver/issues/2346

feat(2346): Update config and model to support job level parameters

---

config/settings.js
test/data/pipeline.update.yaml

Add a boolean value in pipeline settings
- https://github.com/screwdriver-cd/screwdriver/issues/2605
- https://github.com/screwdriver-cd/ui/pull/760
- https://github.com/screwdriver-cd/data-schema/pull/448

feat(2605) Option to display all screwdriver jobs in a chronological order

---

config/settings.js
test/data/pipeline.update.yaml

Add ability to save the preference of show triggers
Add ability to save the preference of show triggers
https://github.com/screwdriver-cd/screwdriver/issues/2610

feat(2610): Add ability to save the preference of show triggers

---

config/provider.js
test/config/job.test.js
test/data/config.job.providereks.yaml
test/data/config.job.providersls.yaml

Provider needs more params for integration builds
This PR adds more properties to provider config

feat: add additional params for provider

---

config/provider.js

Add a few more attributes to support EKS provider config
Add a few more attributes to support EKS provider config

feat: add additional provider attributes

---

api/validator.js
config/base.js
config/regex.js
migrations/20220607-initdb-stages.js
models/index.js
models/stage.js
test/config/base.test.js
test/data/config.base.config.yaml
test/data/config.base.stages.yaml
test/data/stage.yaml
test/data/validator.input.yaml
test/models/stage.test.js

Users might want to group jobs together visually in the UI into stages.
This PR adds stages table to the DB.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2669

feat(2669): Add stage model [1]

---

plugins/notifications.js
test/data/notifications.schemaJobData.yaml
test/plugins/notifications.test.js

Data schema change for notification plugin
Data schema change for notification plugin
https://github.com/screwdriver-cd/screwdriver/issues/2719

feat(2719): Scheduled job stop with notification if there's no admin

---

package.json
screwdriver.yaml

fix: update joi

---

models/buildCluster.js

https://github.com/screwdriver-cd/screwdriver/issues/2852

fix: accept dot in build cluster name

---

plugins/scm.js
test/data/scm.addPrComment.yaml

change comment to an array to support multiple pr comments
https://github.com/screwdriver-cd/screwdriver/issues/2873

feat(2873): allow user to split pr comments

---

migrations/20230721-add-column_group_to_stage.js
models/stage.js
test/data/stage.yaml

Stage will be source of truth for current stage workflowGraph.
This PR adds workflowGraph column to stage model.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2767

fix(2767): Add stage workflowGraph [1.6]

---

api/status.js
test/api/status.test.js
test/data/status-exhaustive.yaml

feat: update api status schema

---

models/pipeline.js

fix schema did not add to `get` and `update` method in previous PR: https://github.com/screwdriver-cd/data-schema/pull/531

fix: add badges to get and update method of pipeline

---

migrations/20231026-add-column_badges_to_pipeline.js
migrations/20231026-add-column_compatibilities_to_command.js
migrations/20231026-add-column_compatibilities_to_template.js

Migration files for 
pipeline `badges`:
https://github.com/screwdriver-cd/data-schema/pull/531
command and template `compatibilities`:
https://github.com/screwdriver-cd/data-schema/pull/532
Add migration files for adding new columns: 
1) pipeline `badges`,
2) command `compatibilities`:
3) command `compatibilities`:
[Sequelize.TEXT](https://sequelize.org/docs/v7/models/data-types/#strings)

fix: add migration files for compatibilities and badges

---

test/config/regex.test.js

Make additions to modification #542
Specify if the test includes common strings and that emojis are also supported.
- https://github.com/screwdriver-cd/screwdriver/issues/2952

fix(2952): Fix test of special characters [2]

---

config/command.js
config/template.js
test/data/config.command.yaml
test/data/config.template.yaml

Update validator schema
https://github.com/screwdriver-cd/command-validator/blob/master/index.js

fix: add compatibilities to validator

---

models/build.js
models/event.js

Swagger's example description is incorrect.
Details are on https://github.com/screwdriver-cd/screwdriver/issues/2368
PR [2] is https://github.com/screwdriver-cd/screwdriver/pull/3035
Fix Swagger's example description.
Specifically, I modified the parentBuildId and Workflowgraph node.
The two typical endpoints involved are as follows.
- [GET /v4/events/{id}](https://api.screwdriver.cd/v4/documentation#/v4/getV4EventsId)
- [GET /v4/builds/{id}](https://api.screwdriver.cd/v4/documentation#/v4/getV4BuildsId)
Before <- -> After
- parentBuildId
- Workflowgraph node
https://github.com/screwdriver-cd/screwdriver/issues/2368
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to …

fix(2368): Fix description in swagger [1]

---

config/settings.js
test/data/user.yaml

Users want to know build results by browser notification.
Add property for browser notification to user-settings.
screwdriver-cd/screwdriver#2369

feat(2369): Add settings schema for notification [1]

---

config/base.js
test/config/base.test.js
test/data/config.base.pipelineTemplate-forbidden.yaml
test/data/config.base.pipelineTemplate-invalid.yaml
test/data/config.base.pipelineTemplate.yaml

Add `template` field and mark currently unsupported field as forbidden when using pipeline template
https://github.com/screwdriver-cd/screwdriver/issues/3020

feat(3020): change to support pipeline template

---

config/base.js
migrations/20240228-add_column_templateVersionId_to_pipeline.JS
models/pipeline.js
test/config/base.test.js
test/data/config.base.config.yaml
test/data/config.base.pipelineTemplate-invalid.yaml
test/data/pipeline.get.yaml

add column templateVersionId to pipeline
add column templateVersionId to pipeline

feat: add column templateVersionId to pipeline

---

models/build.js
models/collection.js
test/data/collection.get.yaml

There are parts where the Data Schema is misaligned with the actual specifications.
I correct some misalignments in response to the following comment on the issue.
```
GET /v4/builds/{id}
The structure of the data is different between the example and the reality. For example, commit information is contained in meta.
GET /v4/collections/{id}
The lastBuilds value is not included.
```
https://github.com/screwdriver-cd/screwdriver/issues/2368#issuecomment-1953634802

fix(2368): Update to match new changes

---

config/base.js
config/pipelineTemplate.js
test/data/config.base.pipelineTemplate-forbidden.yaml
test/data/config.base.pipelineTemplate.yaml
test/data/config.pipelineTemplate.yaml

relax restrictions for pipeline level setting in screwdriver yaml that uses pipeline template
relax restrictions for pipeline level setting in screwdriver yaml that uses pipeline template
https://github.com/screwdriver-cd/screwdriver/issues/3058

feat(3059): Add pipeline level customization for pipeline template

---

config/pipelineTemplate.js
migrations/20220607152947-add_column_state_to_pipeline.js
models/pipelineTemplateVersions.js
test/data/pipelineTemplateVersions.get.allFields.yaml
test/data/pipelineTemplateVersions.yaml

Reverts screwdriver-cd/data-schema#575

Revert "feat(3171): Persist pipeline template workflowGraph in a new column (BREAKING CHANGE)"

---

config/pipelineTemplate.js
migrations/20240827173654-add-workflowgraph-to-pipelineTemplateVersions.js
models/pipelineTemplateVersions.js
test/data/pipelineTemplateVersions.get.allFields.yaml
test/data/pipelineTemplateVersions.yaml

Reverts screwdriver-cd/data-schema#576

feat(3171): Persist pipeline template workflowGraph in a new column. BREAKING CHANGE: adding new column to pipelineTemplateVersions

---

config/pipelineTemplate.js
migrations/20240827173654-add-workflowgraph-to-pipelineTemplateVersions.js
models/pipelineTemplateVersions.js
test/data/pipelineTemplateVersions.get.allFields.yaml
test/data/pipelineTemplateVersions.yaml

Reverts screwdriver-cd/data-schema#578

BREAKING CHANGE: 3171 - Persist pipeline template workflowGraph in a new column

---

package.json

BREAKING CHANGE: Persist pipeline template workflowGraph in a new column.
Add a new column to `pipelineTemplateVersions` table
https://github.com/screwdriver-cd/screwdriver/issues/3171

feat(3171): Forcing major version bump

---

config/base.js
test/data/config.base.stages.yaml

Allow sourcePaths to be set as the stage's configuration.
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/3271
- Related PR: https://github.com/screwdriver-cd/config-parser/pull/178

fix(3271): Allow sourcePaths to be set in stage [1]

---

config/regex.js
core/scm.js
test/data/scm.hook.pr.yaml

SD configuration currently does not support pull_request closed trigger
This PR adds support for pr closed trigger to workflow

feat: add pr closed trigger

---

models/pipeline.js

Pipeline related data is remaining after delete pipeline.
Details - https://github.com/screwdriver-cd/screwdriver/issues/3322
- Add a DELETING state to the pipeline
Issue - https://github.com/screwdriver-cd/screwdriver/issues/3322
PRs
- [2] https://github.com/screwdriver-cd/models/pull/644
- [3] https://github.com/screwdriver-cd/screwdriver/pull/3327

feat(3322): Add a DELETING state to the pipeline to block updates during the pipeline deletion [1]

---

migrations/20250603100312-add-sha-to-job.js
models/job.js
test/data/job.get.yaml
test/data/job.yaml
test/models/job.test.js

Fix https://github.com/screwdriver-cd/screwdriver/issues/3336 .
Add `sha` column into the `jobs` table to check whether the job data is updated or not when start the build.
Issue - https://github.com/screwdriver-cd/screwdriver/issues/3336

feat(3336): add sha column into jobs table [1]
