model/build.js
model/job.js
model/pipeline.js
model/platform.js
model/user.js
test/index.test.js

This PR defines attributes in the data-schema that can be used for automated the creation of tables in a datastore
The models that we need to create tables for now all contain tableName and indexes to create

Define tableName and indexes

---

config/job.js
config/workflow.js

For complex structures like the config, label isn't helping. It's saying Job is broken instead of "main"
With labels:
```js
const Joi = require('joi');
const stepSchema = Joi.string().alphanum().label('Step');
const stepsSchema = Joi.object().keys({
init: stepSchema,
test: stepSchema,
publish: stepSchema
}).label('List of Steps');
const example = {
init: 'foo',
test: 'BAD-THINGS_HERE!!!',
publish: 'bar'
};
Joi.validate(example, stepsSchema).error.toString();
// 'ValidationError: child "Step" fails because ["Step" must only contain alpha-numeric characters]'
```
Without labels:
```js
const Joi = require('joi');
const stepSchema = Joi.string().alphanum();
const stepsSchema = Joi.object().keys({
init: stepSchema,
test: stepSchema,
publish: stepSchema
});
const example = {
init: 'foo',
test: …
```

Labels are throwing off the validator, removing them

---

plugins/executor.js
test/data/executor.start.yaml

This is only temporary until we migrate to just passing `buildId`.

Adding JobName to start (this is really only temporary)

---

package.json
plugins/executor.js
test/data/executor.start.yaml

[Feature](https://github.com/screwdriver-cd/screwdriver/issues/77)
Passing:
- buildId - Build Identifier (to look up stuff)
- container - Container to start in
- apiUri - URI to hit our API
- token - Token to be able to read/write from the API

[F1] New input schema for executor start (1st)

---

api/validator.js
config/job.js
package.json
test/data/config.base.config.yaml
test/data/config.base.jobs.yaml
test/data/config.base.shared.yaml
test/data/config.job.job.yaml
test/data/config.job.steps.yaml
test/data/validator.output.yaml

This has a new format for the validator (to be json valid):
```json
{"name": "install", "command": "npm install"}
```
It also changes the screwdriver.yaml with a new step format:
```yaml
steps:
- npm install
- install: npm install
```

Switching to a new screwdriver.yaml and validator format

---

models/job.js
package.json
test/data/job.update.yaml
test/data/job.yaml

Job schema should have container so when we create builds, we can look up this information

Add container to job schema

---

plugins/scm.js
test/data/scm.getFile.yaml
test/plugins/scm.test.js

When reading a file from source-control it should be possible to pass a reference, i.e. commit, branch, or tag, that will be used for reading the file

Optional ref parameter

---

models/build.js
models/pipeline.js
test/data/build.get.yaml
test/data/build.yaml
test/data/pipeline.get.yaml
test/data/pipeline.yaml

changed from .date() to .string().isoDate() so codegen will work and we ensure compliance with swagger spec for dateTime formatting. http://swagger.io/specification/ and definition of date-time standard. http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14

date to isoDate

---

api/loglines.js

Since our line numbers start at 0, we need to remove this.

I'm positive that 0 is not a positive line number. :(

---

api/loglines.js

Log lines may have no content.

Allow Empty Messages

---

config/job.js
models/secret.js
package.json
test/config/job.test.js
test/data/config.base.config.yaml
test/data/config.base.jobs.yaml
test/data/config.job.secrets.yaml
test/data/secret.create.yaml
test/data/secret.get.yaml
test/data/secret.yaml

This adds secrets to the job configuration.  Example:
```yaml
jobs:
main:
secrets:
- NPM_TOKEN
```
Feature: https://github.com/screwdriver-cd/screwdriver/issues/148

Adding secrets to jobs and renaming the secret value

---

models/build.js
test/data/build.update.yaml

This allows us to get rid of /webhooks/build and replace it with PUT /builds/:id

Allow meta to be passed during update

---

models/build.js
package.json
test/models/index.test.js

Define a primary sorting key for the `build` model.
When you perform a query for a set of build models, they are in a non-specific order. This defines a column to sort the data by.

Define sorting key for build model

---

models/build.js
package.json
test/models/index.test.js

This PR addresses the case where we need to have multiple range keys -- or fewer range keys than indices. We cannot decorate the `indexes` property, since the `rangeKey` property is specific to only one datastore (dynamodb).
Blocked by #51 
Solves https://github.com/screwdriver-cd/screwdriver/issues/187

Define multiple rangeKeys

---

api/pagination.js
models/build.js
plugins/datastore.js
test/data/build.get.yaml
test/data/build.yaml
test/data/pagination.yaml

Add `sort` to the allowed keys. This prepares for the datastore change so that we can sort
Solves https://github.com/screwdriver-cd/screwdriver/issues/187

Allow sort in the scan config

---

models/job.js
package.json
test/data/job.get.yaml

This PR adds an archive attribute to the job model. The purpose of this additional field is to flag a specific job as active or archived. Related to screwdriver-cd/screwdriver#188
Jobs that are associated with open PRs workflow jobs are considered to be active. 
Jobs that are associated with closed/merged PRs or are jobs used outside of the workflow are considered to be archived.

[1] Add "archive" attribute to job model

---

models/pipeline.js
package.json
test/data/pipeline.create.yaml

This PR allows to store scmRepo object to a pipeline. 
(screwdriver-cd/screwdriver#194 and screwdriver-cd/screwdriver#160)

Allow to store scmRepo object to pipeline

---

models/pipeline.js
test/data/pipeline.create.yaml
test/data/pipeline.get.yaml
test/data/pipeline.update.yaml
test/data/pipeline.yaml

We have 0 code in our system for `configUrl` right now, so I'm removing it until we want to bring it back.
Additionally, we need to return `scmRepo` as part of the GET and we dont' want users to pass it to us during create, it's a auto-generated value.

Fixing the pipeline model for scmRepo and removing configUrl

---

models/secret.js
test/data/secret.remove.yaml
test/data/secret.update.yaml
test/models/secret.test.js

- Add `update` schema to secret to allow update on `value` or/and `allowInPR`
- Remove `remove` schema from secret since we are not using it
First PR in  [Issue #232](https://github.com/screwdriver-cd/screwdriver/issues/232)

Add update secret schema

---

api/validator.js
test/api/validator.test.js
test/data/validator.erroroutput.yaml

Right now we have no way of surfacing parse errors from the API. This PR adds another key to the output `errors` to contain any parse errors. This will allow a future validator UI to more easily display these errors.

Allow validator output to contain a list of errors.

---

plugins/scm.js
test/data/scm.getFileRef.yaml
test/plugins/scm.test.js

-  `scm.getFile(`) will either use `scmUri` or `prRef` to get file
- Add an extra schema for scm.getFile() when it takes in `prRef` instead of `scmUri`

add getFileRef schema for scm.getFile() to take in prRef

---

plugins/scm.js
test/data/scm.getFile.yaml
test/data/scm.getFileRef.yaml
test/plugins/scm.test.js

Not using this anymore. Should be merged after https://github.com/screwdriver-cd/scm-base/pull/19

[3] Revert "add getFileRef schema for scm.getFile() to take in prRef"

---

core/scm.js
test/data/scm.hook.yaml

- Add event uuid to parseHook schema
- It will be needed in API when we switch to parseHook for getting all event data
- https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/github.js#L339

Add event uuid to scm parseHook schema

---

CHANGELOG.md
models/build.js
package.json
test/data/build.get.yaml

Builds should know which event they are associated with; updating build schema to include an `eventId` when a GET request is made 
Related to https://github.com/screwdriver-cd/screwdriver/issues/221

Add eventId to build schema

---

models/event.js
test/data/event.get.full.yaml
test/data/event.get.yaml
test/data/event.yaml

Let's remove event status for now to simplify the logic of the API. 
We can infer the status of an event from the builds' status.

Remove event status

---

CHANGELOG.md
models/build.js

In order to incrementally add events to the API, we need to make the `eventId` an optional field for build get.

Make eventId an optional field when getting a build

---

CHANGELOG.md
package.json
plugins/scm.js
test/data/scm.getCheckoutCommand.yaml
test/plugins/scm.test.js

- We will generate checkout command in SCM plugin with `getCheckoutCommand` method
- This schema is used to validate the input for `getCheckoutCommand` method
Relates to https://github.com/screwdriver-cd/screwdriver/issues/312

Add schema to validate input for `getCheckoutCommand` in scm

---

CHANGELOG.md
core/scm.js
package.json
test/core/scm.test.js
test/data/scm.command.yaml

We will require scm-plugins to output `sd-checkout-code` as the name for a checkout command
Related to feedback in https://github.com/screwdriver-cd/models/pull/132

[1] Add checkout command output validation for scm plugins

---

plugins/scm.js
test/data/scm.addWebhook.yaml
test/plugins/scm.test.js

Joi validation for `scm-base.addWebhook`, which will help enforce the input for the method.
Based on the implementations for [`scm-github`](https://github.com/screwdriver-cd/scm-github/pull/45) and [`scm-bitbucket`](https://github.com/screwdriver-cd/scm-bitbucket/pull/29), we determined that the most common interface between them contains:
* `scmUri` - the SCM URI of the repository
* `token` - the auth token to interact with the SCM service
* `url` - the webhook to notify when certain events occur
Related to screwdriver-cd/screwdriver#379

feat: addWebhook method input

---

models/event.js
test/models/event.test.js

- datastore-sequelize's `scan` method will set the `sortKey` for the index `type`, which is `null` now. This will cause error when querying the database.
- Change the sortKey to `createTime` 
https://github.com/screwdriver-cd/datastore-sequelize/blob/master/index.js#L327

fix: add rangeKey for event

---

plugins/datastore.js
test/data/datastore.id.yaml

This is because we should be able to lookup based on unique keys, not just the ID

fix(399): Datastore get should not require `id` anymore

---

plugins/scm.js
test/data/scm.addWebhook.yaml

This is a bug: https://github.com/screwdriver-cd/models/blob/master/lib/pipeline.js#L122
Related: https://github.com/screwdriver-cd/screwdriver/issues/379

fix: model passes in webhookUrl for add webhooks

---

config/index.js
config/regex.js
config/template.js
test/config/regex.test.js
test/config/template.test.js
test/data/config.template.yaml

We will need to add schemas for what is expected/valid in a ```template.yaml```
Expected/required fields in a `template.yaml`:
- name (eg: chef/cookbook, chef/pipeline-upload, chef/pipeline-assembly, etc.)
- description
- version
- maintainer/point of contact
- config
- steps
Related to https://github.com/screwdriver-cd/screwdriver/issues/470
TODO (in another PR): add `lifespan` schema

feat(470): Add template validation

---

config/template.js
models/index.js
models/template.js
test/data/template.create.yaml
test/data/template.get.yaml
test/data/template.update.yaml
test/data/template.yaml
test/models/template.test.js

- Add template schema to models
- Highlight:
-  `scmUri` is the template pipeline's scmUri
- `name` and `version` define a unique record
-   A record (e.g. test-template@1.3) can have multiple `labels`
-  only `labels` can be updated for a record
Related to https://github.com/screwdriver-cd/screwdriver/issues/470

feat(470): add template schema to models

---

api/index.js
api/templateValidator.js
test/api/templateValidator.test.js
test/data/template-validator.erroroutput.yaml
test/data/template-validator.input.yaml
test/data/template-validator.output.yaml

An API endpoint is being implemented for a user to validate their template configuration.
This change will introduce a schema for both input & output for the API to utilize.
It will take a template configuration in the form of a string as input, similar to how the [validator endpoint does](https://github.com/screwdriver-cd/data-schema/blob/master/api/validator.js#L60). 
The output will be an object consisting of the interpreted template configuration and any errors encountered while validating it. A pseudo-code example:
```
{
template: {
...
},
errors: [
..
]
}
```
* The `template` field is a general `Joi.object()` because the passed-in template could be parseable and still be an invalid Screwdriver template. 
* Contributes to screwdriver-cd/screwdriver#470
* Related to …

feat(470): adding input & output schema for template validation API endpoint

---

config/template.js

This issue is same as https://github.com/screwdriver-cd/screwdriver/issues/325 and https://github.com/screwdriver-cd/data-schema/pull/102. 
I fixed same way.
If the max value are not appropriate, please tell me.
```
api_1    | error:  SequelizeDatabaseError: ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT column 'name' used in key specification without a key length
api_1    |     at Query.formatError (/usr/src/app/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
api_1    |     at Query._callback (/usr/src/app/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
api_1    |     at Query.Sequence.end (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
api_1    |     at Query.ErrorPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
api_1 …
```

fix: add length to template for mysql index

---

config/job.js
config/regex.js
test/config/job.test.js
test/data/config.job.template.bad.yaml
test/data/config.job.template.good.yaml

This is for the user's side, when they specify `template` inside their `screwdriver.yaml`
This will probably be used by the `config-parser` here https://github.com/screwdriver-cd/config-parser/blob/master/lib/phase/structural.js
Related: https://github.com/screwdriver-cd/screwdriver/issues/470

feat(470): allow template field in screwdriver.yaml

---

models/template.js
test/data/template.get.yaml
test/data/template.yaml

This was brought up by @stjohnjohnson  a while ago. 
Since we use `id` to identify a pipeline, we should just use it here instead of `scmUri`
This is a breaking change, it will break all the existing templates right now. But since all the templates we have are test templates that were created by me, I just emptied the table.

fix: template ties to pipelineId instead of scmUri

---

README.md

The previous PR bumped major version, which requires all other packages to use the new data-schema (otherwise API build will fail due to duplicate package found). 
We actually didn't need to bump major (since technically it wouldn't break other people), so I unpublished the major version. Making this change so it will bump to `16.5.2` instead

fix: bump patch

---

config/template.js
test/config/template.test.js
test/data/config.template.bad.yaml

Even though `'config.steps'` is already in the required keys for template `Joi.object`, it turns out that `'config'` itself needs to be required. Currently, this is not valid:
```yaml
name: template/test
version: 1.0.0
description: Publishes the template yaml from sd-template.yaml
maintainer: tiffanykyi@gmail.com
config:
image: node:6
```
But this is valid:
```yaml
name: template/test
version: 1.0.0
description: Publishes the template yaml from sd-template.yaml
maintainer: tiffanykyi@gmail.com
```

fix: Add config to required keys for template

---

config/job.js
models/build.js
test/data/config.job.steps.yaml
test/data/step.get.yaml

Allows users to define a step verbosely in their `screwdriver.yaml`, to make it possible for an `alwaysRun` flag to exist:
```yaml
jobs:
main:
steps:
- name: hello
command: echo hello
alwaysRun: true
```
After this is merged, I'll be able to test the `config-parser` changes properly
Related to https://github.com/screwdriver-cd/screwdriver/issues/473

feat(473): Enable alwaysRun flag on steps

---

api/validator.js
config/job.js
test/data/validator.output.yaml

Pipeline is currently failing due to this: https://cd.screwdriver.cd/pipelines/1/builds/3615
We need to allow this field for the validator output. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/473

fix: allow alwaysRun in validator output

---

api/validator.js

Our pipeline is failing at beta functional test:
Cuz it has alwaysRun in job permutation and we revert all changes so that job cannot be retrieved correctly. Allow it for now and when it run through the pipeline, alwaysRun flag will be removed. Then we can revert this.

fix: allow alwaysRun field for now to fix the pipeline

---

plugins/scm.js
test/data/scm.getCommitSha.yaml

fix: add `prNum` as optional to getCommitSha
`prNum` is optional and can be `null` since the` job` model may return null if it is not a PR:
https://github.com/screwdriver-cd/models/blob/master/lib/job.js#L93
This change is backward compatible.
Related to https://github.com/screwdriver-cd/screwdriver/issues/244

fix: add prNum as optional to getCommitSha

---

models/build.js
test/data/build.update.yaml

Users (and admins) will want builds to timeout after some period of time to free up compute nodes. 
This PR adds a new field that can be used to store a date, after which the build should be aborted automatically due to a timeout.
Relates to issue #545

feat(545): Add a field for builds to know when to timeout

---

README.md
models/token.js
test/data/token.yaml

* In the readme.md, I updated the number in brackets last time but forgot to update the word, so it said "seven (8)"
* token.value is clearer than token.token, and matches the naming of the secrets schema

Fix a typo in readme, change a field name for clarity and consistency

---

screwdriver.yaml

The github squash and merge from this PR https://github.com/screwdriver-cd/data-schema/pull/130 created a new commit message, and it didn't conform with semantic-release. So `publish` job failed because it couldn't find a version change: https://cd.screwdriver.cd/pipelines/12/builds/4263

fix: Edit comments

---

models/token.js
test/data/token.yaml

We have realized that we don't need to actually store the token value.
The token can be validated by checking it with a public key. It also contains information about the user, to check that they have access to whatever resource they're requesting.
Then the only thing left to do is to check that the user has not revoked the token, which can be done by comparing the uuid in the token against a list of uuid's of valid tokens in the datastore.
Then we don't need to worry about keeping a list of unsealed tokens on the user object. Sealing the incoming token and comparing to the sealed values of the tokens doesn't work, as iron checks the current time as part of sealing.

fix: Don't store token value, do store a uuid to allow tokens to be revoked

---

models/token.js
test/data/token.yaml

* Need to index on the hashed value so we can look it up easily
* Not using iron means we can specify exactly what the hashed value should look like

fix: Validate hashed token value

---

models/token.js

Name/username uniqueness can be checked manually in the API.
In order to be able to call `tokenFactory.get({ hash })` and not have to reimplement the base `get` function the schema has to say that hash is a unique column.

fix: Tokens are unique by hash

---

models/token.js

The datastore wasn't validating tokens that hadn't been used, because the `.allow(null)` was being ignored by the datastore-sequelize plugin. Now using empty strings instead of `null`.

fix(tokens): Sequelize didn't like null values

---

models/token.js
test/data/token.yaml

* the default base64 encoding uses `+`, `/`, and `=`
* replace those with `_`, `-`, and `~`

fix(tokens): Use url-safe base64 encoding

---

models/token.js
test/data/token.yaml

Didn't see @FenrirUnbound's [comment](https://github.com/screwdriver-cd/data-schema/pull/140#discussion_r120495728) until after the last PR was merged. He has a good point about the relative merits of using a library versus a function defined in the models files.
Notably, it changes how long the hashes we're storing are, because that library replaces `=` with nothing as opposed to a `~`.

fix(tokens): Use base64url library for encoding

---

models/build.js
test/data/build.update.yaml

Users (and admins) will want builds to timeout after some period of time to free up compute nodes. 
This PR adds a new field that can be used to store a date, after which the build should be aborted automatically due to a timeout.
* Relates to issue https://github.com/screwdriver-cd/screwdriver/issues/545
* Duplicates PR #127 in the hope that the `alter table` issue is fixed when https://github.com/screwdriver-cd/datastore-sequelize/pull/18 is merged.

feat(545): add field to timeout builds

---

plugins/scm.js
test/data/scm.updateCommitStatus.yaml

We need the pipelineId to distinguish different pipelines, when subdirectory is supported. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/471

fix: allow pipelineId in updateCommitStatus

---

plugins/executor.js
test/data/executor.startNoAnnotations.yaml
test/plugins/executor.test.js

Adding annotations to the start schema for executors. This will allow people to send annotations to specify which executor to use when starting a build.
Example annotations yaml segment:
```
annotations:
beta.screwdriver.cd/executor: k8s
```
Related to https://github.com/screwdriver-cd/screwdriver/issues/604

fix(604): Add annotations to executor start

---

models/pipeline.js
test/data/pipeline.update.yaml
test/models/pipeline.test.js

Users currently cannot update the repo/branch for their pipeline.
This PR adds a schema for updating a pipeline. We're keeping it as a `checkoutUrl` since it is more user friendly.
https://github.com/screwdriver-cd/screwdriver/issues/562

fix(562): Add schema for updating a pipeline

---

plugins/executor.js
test/data/executor.stop.yaml

Executor stop needs to be able to take in `annotations`
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/604
Related to https://github.com/screwdriver-cd/screwdriver/pull/607

fix(604): Add annotations to executor stop

---

models/token.js
test/data/token.update.yaml

Currently any attempt to update a token to have an empty description will fail because Joi won't validate it. Joi's `any.optional()` allows `undefined`, but not `''`.
Allow users to set the description of their tokens to be empty.
https://github.com/hapijs/joi/blob/v10.6.0/API.md#anyoptional

fix(tokens): Allow token descriptions to be set to empty

---

models/collection.js
models/index.js
test/data/collection.create.yaml
test/data/collection.createWithDescription.yaml
test/data/collection.createWithPipelineIds.yaml
test/data/collection.get.yaml
test/data/collection.update.yaml
test/data/collection.yaml
test/models/collection.test.js

Schema validation for Collections
This PR adds a schema for Collections along with tests to be used for the creation of a CRUD API for collections
issue: [screwdriver-cd/screwdriver#523](https://github.com/screwdriver-cd/screwdriver/issues/523)

feat(523): Add collection schemas and tests

---

models/collection.js

Since id is auto-incremented and thus unique, it makes more sense to
have the keys be `userId` and `name` as a User should not have 2
collections with the same name.
To set `userId` and `name` as the unique fields for a row as we do not want to allow a particular user to have 2 collections with the same name.
Pull Request: [screwdriver-cd/models#178](https://github.com/screwdriver-cd/models/pull/178#pullrequestreview-49010254)
Feature issue: [screwdriver-cd/screwdriver#523](https://github.com/screwdriver-cd/screwdriver/issues/523)

fix(collections): Change keys in collections schema

---

models/index.js
models/template.js
models/templateTag.js
test/data/templatetag.create.yaml
test/data/templatetag.yaml
test/models/templatetag.test.js

Add a Template Tag model, which consists of name, tag, and version. 
Example: `mytemplate@1.2.0` can be tagged as `stable` and `latest`
In the templateTags table, there will be a record that looks like 
| id | name | tag | version | 
|---|---|---|---|
| 1 | mytemplate | stable | 1.2.0 | 
| 2 | mytemplate | latest | 1.2.0 | 
If they want to change `stable` to `1.1.0`, then the table will look like 
| id | name | tag | version | 
|---|---|---|---|
| 1 | mytemplate | stable | 1.1.0 | 
| 2 | mytemplate | latest | 1.2.0 | 
Related: https://github.com/screwdriver-cd/screwdriver/issues/616

feat: add template tag

---

models/templateTag.js

We would like to add an endpoint for deleting template tags.
This PR adds a schema for the delete endpoint for template tags.
- Template tag data schema PR: https://github.com/screwdriver-cd/data-schema/pull/157
- Original issue: https://github.com/screwdriver-cd/screwdriver/issues/616

fix(616): Add remove schema for template tags

---

models/pipeline.js
models/user.js
test/data/pipeline.get.yaml
test/data/pipeline.yaml
test/data/user.create.yaml
test/data/user.yaml

This PR add `scmContext` to models.It is a change for the support multiple SCMs.
`scmContext` determines that an user is currently logged into by which scm.

feat(365): Add scmContext to models

---

models/pipeline.js
models/user.js
test/data/pipeline.get.yaml
test/data/pipeline.yaml
test/data/user.create.yaml
test/data/user.yaml

Revert https://github.com/screwdriver-cd/data-schema/pull/152 because of failing build https://cd.screwdriver.cd/pipelines/1/builds/7373 
We need other component (api, model. scm-XXX) update  before merge.
Related: https://github.com/screwdriver-cd/screwdriver/issues/365

Revert "feat(365): Add scmContext to models #152"

---

models/collection.js
test/data/collection.get.yaml

Currently, the GET schema is designed to only return an array of
pipeline IDs but it would make more sense if the GET for a collection
returned an array of the pipeline objects.
This PR changes the GET schema of collection so that an array of pipeline objects are sent back when a collection is requested instead of just the IDs for the pipelines in that collection
issue: [screwdriver-cd/screwdriver#523](https://github.com/screwdriver-cd/screwdriver/issues/523)

fix(collections): Change the GET schema to include pipelines

---

models/templateTag.js
test/data/templatetag.create.yaml
test/data/templatetag.remove.yaml
test/models/templatetag.test.js

Remove these since we changed the endpoints. They are no longer needed in https://github.com/screwdriver-cd/screwdriver/commit/7d342943b10b58312a411902f842bf0a51d2ae56
Related: https://github.com/screwdriver-cd/screwdriver/issues/616

fix: remove schema for delete and create tag

---

config/regex.js
config/template.js
models/templateTag.js
test/data/templatetag.yaml

Adding regex to restrict template tags to have to start with an alpha character, as a part of a discussion from another PR.
**Discussion link:** https://github.com/screwdriver-cd/screwdriver/pull/646/files/d3ae5f42193833e1d0bc0cdd208d7bf2c4c3a3d3#r128141572
**PR:** https://github.com/screwdriver-cd/screwdriver/pull/646
**Issue:** https://github.com/screwdriver-cd/screwdriver/issues/616

fix(616): Add regex for template tag names

---

models/collection.js
test/data/collection.list.yaml
test/models/collection.test.js

Due to the difference in the structure of a collection object in the GET and LIST API responses, we need a separate schema for LIST. In the LIST request, the UI will primarily require id, name, and description for each of the user's collections. The GET request will populate all the pipelineIds with the pipeline objects instead.
This PR adds a schema for the LIST request along with a unit test.
issue: [screwdriver-cd/screwdriver#523](https://github.com/screwdriver-cd/screwdriver/issues/523)

fix(collections): Add list schema for collections

---

config/regex.js
config/template.js
models/templateTag.js
test/config/job.test.js
test/data/config.job.template-with-label.good.yaml
test/data/config.job.template-with-tag.good.yaml
test/data/config.job.template.good.yaml

Full template names should follow the format: `<TEMPLATE_NAME>@<VERSION>` or `<TEMPLATE_NAME>@<TEMPLATE_TAG_NAME>`, like `chef/publish@1.2.3` or `chef/publish@stable`. We will also accept `<TEMPLATE_NAME>` or `<TEMPLATE_NAME>@`. The models should handle the logic for those cases.
This PR makes the change to the full template name regex.
Related to https://github.com/screwdriver-cd/screwdriver/issues/616

fix(616): Update full template name

---

config/regex.js

Current regex not good; new regex **gooder**.
Due to comments based on https://github.com/screwdriver-cd/data-schema/pull/165
Related issue: https://github.com/screwdriver-cd/screwdriver/issues/616

fix(616): Fix template and version regexes

---

models/token.js
test/data/token.yaml

It has been suggested that we use 512 bit hashes to store tokens.
Increase the hash length in the database

fix(tokens): increase hash size to 512 bits

---

config/base.js
test/data/config.base.config.yaml

This adds an optional field in the base config to allow us to hint about
what version the config is.

feat: Allow Multiple-Documents

---

models/collection.js
models/pipeline.js
test/data/collection.get.yaml
test/data/pipeline.get.yaml

For the UI, it needs information about the last build health for the dashboard.
This PR changes the data schema for collection.get to add a lastBuilds field to the pipeline object in the response. It also adds a lastEventId field to the pipeline.get to cache the last event for a pipeline.
Related: [screwdriver-cd/screwdriver#714](https://github.com/screwdriver-cd/screwdriver/pull/714)
Issue: [screwdriver-cd/screwdriver#523](https://github.com/screwdriver-cd/screwdriver/issues/523)

feat(collections): Add lastBuilds to pipeline. BREAKING CHANGE

---

models/collection.js

Allows descriptions to be an empty string

fix(collections): Allow empty string for description

---

models/collection.js
test/data/collection.get.yaml

For the user dashboards, we want to display information about the number of PRs open and failing for each pipeline in the collection.
This PR adds pr info to each pipeline in the GET for a collection
Issue: [screwdriver-cd/screwdriver#523](https://github.com/screwdriver-cd/screwdriver/issues/523)

feat(collections): Add pr info to pipelines in collections get schema

---

models/template.js

If sorted by version, 1.0.10 than 1.0.9 it will be priority.
https://api.screwdriver.cd/v4/templates/tifftemplate
In this case, the following processing will feel unnatural.
https://github.com/screwdriver-cd/models/blob/4ec55e60c934f945b3350d569c7164db2bef7b32/lib/templateFactory.js#L126
I think that sorting by id will result in the expected behavior.

feat: sort by id

---

screwdriver.yaml

The same as [this](https://github.com/screwdriver-cd/circuit-fuses/commit/9b4300dc6fe0158c587ba4f1f33f119d6b7cd46c#diff-e917068babdeb1068c2aa1a34cb665ca).

fix: pin semantic release back and do not save dependency

---

config/job.js
models/event.js
test/data/event.create.full.yaml
test/data/event.get.full.yaml
test/models/event.test.js

- Add a optional `startFrom` field to event
- Add `create` event schema for new `POST /event` endpoint
Related: https://github.com/screwdriver-cd/screwdriver/issues/723

feat: add optional startFrom field to event

---

models/event.js

`requiresValue` is using `Joi.alternatives`, when sequelize tried to save it to the datastore, it does not know how to process it.
Change it to string. Only use the `requiresValue` schema for create request

fix: store startsFrom as string in datastore

---

api/validator.js
config/index.js
config/workflowGraph.js
models/event.js
models/pipeline.js
test/config/workflowGraph.test.js
test/data/config.workflowGraph.unknown.yaml
test/data/config.workflowGraph.yaml
test/data/event.get.full.yaml
test/data/validator-with-requires.output.yaml

Store graph generated by [workflow-parser](https://github.com/screwdriver-cd/workflow-parser) into a new optional field `workflowGraph` in both event and pipeline
- Add an optional field `workflowGraph` to `pipeline` and `event` model
- Allow `workflowGraph` in output generated by config-parser (used by API `validator`)
For legacy workflow config:
- Pipeline and events will have both workflow and workflowGraph
For new workflow config:
- Pipeline and events will only have workflowGraph
Related to https://github.com/screwdriver-cd/screwdriver/issues/723

feat: add workflowGraph to pipeline and events

---

config/regex.js
models/job.js
test/config/regex.test.js
test/data/job.pr.get.yaml
test/models/job.test.js

- allow `PR-1:main` as job name in job model
- in user yaml, jobNames start with `PR-` are not allowed so we do not take care of cases like `PR-1-main` in job model
- add a regex only for PR job name
- will be used later to parse PR job name

feat: allow PR-1:main as job name in model

---

models/event.js
test/data/event.create.pr.yaml
test/models/event.test.js

allow event startFrom PR-1:main
When user go to the UI and try to restart a specific PR job, e.g.`PR-1:main`, they should be able to do it.
To unblock https://github.com/screwdriver-cd/screwdriver/pull/762

fix: allow event startFrom PR-1:main

---

config/base.js
test/data/config.base.config.yaml

We are using this schema to validate user yaml and makes `main` as requried.
https://github.com/screwdriver-cd/config-parser/blob/master/lib/phase/structural.js#L4
Removes the `main` job requirement from here and add it to the `config-parser` to check only against legacy config.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/723

feat(723): make main not required in jobs

---

config/regex.js
test/config/job.test.js
test/config/regex.test.js
test/data/config.job.jobv2.externalrequires.yaml

We want to allow this so that the pipeline will be rebuilt when sd@pipelineId:jobName completes successfully
Related https://github.com/screwdriver-cd/screwdriver/issues/770

feat(770): allows sd@pipelineId:jobName for requires

---

config/regex.js
test/config/regex.test.js

- Users can name their repository with `.`, e.g. 'my.repo'.
The old regex for `checkoutUrl` will fail that.
Fixed it to allow that. Regex credit to @jithin1987!
Previously `https://github.com/screwdriver-cd/.git` will be invalid.
Now with the new regex, it's valid but when it goes through `create pipeline`, user will get err `repo does not exist`. I think that's good enough.

fix: allow . in repoName for checkoutUrl

---

models/trigger.js

This is the same issue as #102 and #114 .
I added max length to 'src' in trigger.js.
```
error:  SequelizeDatabaseError: BLOB/TEXT column 'src' used in key specification without a key length
at Query.formatError (/usr/src/app/node_modules/sequelize/lib/dialects/mysql/query.js:223:16)
at Query.connection.query [as onResult] (/usr/src/app/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
at Query.Command.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:30:12)
at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:515:28)
at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:94:16)
at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:77:14)
at Socket.<anonymous> …
```

fix: add length for mysql index.

---

api/validator.js
test/data/validator-with-requires.output.yaml

We should not require main job in validator output since new workflow won't have it.
Resolves https://github.com/screwdriver-cd/screwdriver/issues/792

fix: do not require main job in validator output

---

config/command.js
models/command.js
models/commandTag.js
test/data/command.create.yaml
test/data/command.get.yaml
test/data/command.yaml
test/data/commandTag.yaml
test/data/config.command.bad.yaml
test/data/config.command.yaml

Screwdriver Commands feature.
Rename `command` key of the `command` data schema to `name`.
- It may be necessary to recreate `commands` and `commandTags` tables, if those old schema tables already exist.
- [Design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md) 
- https://github.com/screwdriver-cd/screwdriver/pull/829

fix: rename `command` key to `name`.

---

models/command.js
test/data/command.get.yaml
test/data/command.yaml

Like `template`, to limit a pipeline which updates the command only a pipeline which created the command, I add a `pipelineId` to the `command`.
Add a pipelineId to the command schema.

feat: add pipelineId to command

---

models/command.js

Sharing Commands implementation.
This PR add a missing rang key to the command model so many as index keys. 
If these range keys are not enough, Sequelize's data scan fails.
```
data: TypeError: Cannot read property '_modelAttribute' of undefined
```

fix: add a missing range key to the command model.

---

test/models/index.test.js

Unit tests improvement.
This PR adds match up test of `indexes` and `rangeKeys` properties about each model.
This test will prevent new added model's bug like this.
- https://github.com/screwdriver-cd/data-schema/pull/200

test: add match up test of indexes and rangeKeys.

---

api/commandValidator.js
api/templateValidator.js
test/data/command-validator.erroroutput.yaml
test/data/template-validator.erroroutput.yaml

Need to update the Joi error path to array of strings due to Joi v13 change.
Related to https://github.com/screwdriver-cd/screwdriver/pull/884

fix: Update joi error path to array

---

models/event.js
test/data/event.create.full.yaml
test/data/event.get.full.yaml

Adding a parentEventId so we can fetch meta from the parent event when trying to run a detached build.
This PR adds an optional parentEventId to the GET and CREATE schemas for an event.
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/806

fix: Add parentEventId to events model

---

core/scm.js
test/data/scm.hook.pr.yaml

This field will indicate the source of the pull request (branch or
fork).  That way we can do some magic around automatically starting the
pr build or not.
_note: I did not make the field required, that ensures it's backwards compatible with other plugins_
Related to: https://github.com/screwdriver-cd/screwdriver/issues/579

feat(579): Exposing new field `source`

---

models/job.js

Job name is too short and a shown error message "Data too long for column 'name' at row 1"  is hard to understand.
Related: https://github.com/screwdriver-cd/screwdriver/issues/890

fix(890): increase job name max length

---

models/build.js
test/data/build.yaml

As a part of updating the metadata used in builds, we want to merge together meta from all parentBuildIds when running a join job.
This PR allows the `parentBuildId` key to be a single number or an array of numbers (for backwards compatibility.
~This PR adds a `parentBuildIds` key which will be an array of parentBuildIds. Golang cannot handle multiple types for fields and we want to make sure our change is backwards compatible.~
Also adding `CREATED` status so the join build can be populated with `parentBuildId`s before starting.
Related to https://github.com/screwdriver-cd/screwdriver/issues/904

fix: Allow parentBuildId to be an array of ids

---

models/build.js
models/event.js

sequelize doesn't know how to deal with `Joi.alternatives` when it tries to save the field into the database. Change the field to array so that it will be mapped to `TEXT`. https://github.com/screwdriver-cd/datastore-sequelize/blob/master/index.js#L98
But for validation, to be backward compatible, we still use `Joi.alternatives` to validate. So that a single parentBuildId value will still work.

fix: remove joi.alternatives in build model

---

models/event.js
test/data/event.create.restart.yaml
test/models/event.test.js

- add an optional field `buildId` to event create schema so that UI only need to send in `buildId` to restart a job
- will remove the stuff we don't need later, e.g. `parentBuildId`, `parentEventId` later. Just keep them here for now to make it backward compatible.

fix: add an optional field `buildId` to event create schema

---

models/build.js
models/event.js
test/models/build.test.js
test/models/event.test.js

There is a bug that causes builds to break if you run a detached job after an event occurs with no builds run (e.g., if someone makes a change to the screwdriver.yaml without triggering any builds). The code will try to marshal the meta and no meta will exist in the parent event.
This PR adds a default empty object to `meta` in builds and events.
- Related to the event meta work: https://github.com/screwdriver-cd/screwdriver/issues/904

fix: Add default value for meta field

---

api/validator.js
config/job.js
test/config/job.test.js
test/data/config.job.sourcePaths.yaml
test/data/validator.input.yaml
test/data/validator.output.yaml

Users don't always want builds to be triggered for all files in their repositories. Sometimes it would be nice if they could just configure certain source paths in their repos.
This PR adds the `sourcePaths` keyword to job configs. It can either be an array of strings or a string.
Related to https://github.com/screwdriver-cd/screwdriver/issues/911

fix(911): Add sourcePaths to job config and validator

---

core/scm.js
plugins/scm.js
test/data/scm.getChangedFilesInput.yaml
test/data/scm.getChangedFilesOutput.yaml
test/data/scm.hook.ping.yaml
test/data/scm.hook.pr.yaml
test/data/scm.hook.push.yaml
test/plugins/scm.test.js

We'd like to add a method to scm-base that gets a list of changed files when a push or PR occurs in Git. This will allow for subdirectory support.
This PR:
- alphabetizes the keys in the **parseHook** schema
- adds `lastCommitMessage` and `scmContext` to the parseHook schema
- adds input/output validation for **parseHook** and **getFilesChanged** methods
- Related to https://github.com/screwdriver-cd/screwdriver/issues/911

feat(911): Add validation for scm methods parseHook and getChangedFiles [1]

---

core/scm.js

Previously, we didn't validate using `SCHEMA_HOOK`. Now it's actually validating `SCHEMA_HOOK` and it is giving some issues, since certain action will not have the field. For example, `lastCommitMessage` can be `empty` for a closed PR.

fix: allow empty string for parseHook

---

plugins/scm.js
test/data/scm.getChangedFilesInput.yaml

scm-router will pass in `scmContext` to _getChangedFiles.
This PR allows for scmContext for getChangedFiles input.
Related to https://github.com/screwdriver-cd/screwdriver/issues/911
Related to https://github.com/screwdriver-cd/screwdriver/pull/956

fix(911): Add scmContext to input schema for getChangedFiles

---

plugins/scm.js
test/plugins/scm.test.js

If an scm plugin does not have getChangedFiles implemented, they should return null. That way, we will know that they do not support the source paths feature.
This PR allows getChangedFiles to return null.
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/911

fix(911): Allow null output for getChangedFiles

---

core/scm.js
test/data/scm.parseHook.yaml

scm-gitlab returns null for hookId.
This PR allows null for hookId.
scm-gitlab: https://github.com/tkyi/scm-gitlab/blob/master/index.js#L320
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/911

fix: Allow null for hookId

---

api/auth.js
api/index.js
api/stats.js
api/status.js
api/versions.js
test/api/auth.test.js
test/api/stats.test.js
test/api/status.test.js
test/api/versions.test.js
test/data/auth.contexts.yaml
test/data/stats.yaml
test/data/status.yaml
test/data/versions.yaml

There are response object schemas missing for several endpoints as detailed in https://github.com/screwdriver-cd/screwdriver/issues/115
Create schemas for:
Swagger documentation:
https://api.screwdriver.cd/v4/documentation

fix(115): Add schemas for versions, auth contexts, stats, and status

---

api/validator.js
test/data/job.yaml

Expose the job SCM object in permutations.
https://github.com/screwdriver-cd/screwdriver/issues/1041

feat(1041): Include job SCM schema in validator permutations

---

plugins/scm.js
test/data/scm.getCheckoutCommand.yaml

In order to pass the `screwdriver.cd/repoManifest` annotation to `_getCheckoutCommand` we include the field as part of the schema.
https://github.com/screwdriver-cd/screwdriver/issues/1041

feat(1041): Include manifest in GET_CHECKOUT_COMMAND schema

---

config/regex.js
config/template.js
core/scm.js
models/template.js
models/templateTag.js
test/api/templateValidator.test.js
test/config/regex.test.js
test/config/template.test.js
test/data/config.template.badWithNamespace.yaml
test/data/config.template.withNamespace.yaml
test/data/template-validator.inputWithNamespace.yaml
test/data/template.createWithNamespace.yaml
test/data/template.getWithNamespace.yaml
test/data/template.updateWithNamespace.yaml
test/data/templatetag.withNamespace.yaml
test/models/template.test.js
test/models/templatetag.test.js

We would like to group templates by namespace, but we don't explicitly define it anywhere.
This PR adds the `namespace` field to templates similar to command namespaces.
Also adds template full name regex that will group for namespace.
Related to https://github.com/screwdriver-cd/screwdriver/issues/926

fix(926): Add template namespace [1]

---

api/templateValidator.js
config/regex.js
config/template.js
core/scm.js
test/config/regex.test.js
test/config/template.test.js
test/data/config.template.badName.yaml
test/data/config.template.badNameWithSlash.yaml

Should only allow one slash in the template name. If the template namespace exists, template name should not have any slashes.
Related to https://github.com/screwdriver-cd/screwdriver/issues/926#issuecomment-391907638

fix(926): Add extra logic for template name schema

---

.gitignore
config/job.js
config/regex.js
test/config/regex.test.js
test/data/config.job.blockedBy.bad.yaml
test/data/config.job.blockedBy.yaml

Since blockedBy is always using OR logic, we should at least make it consistent with previous workflow syntax by requiring a tilde before all the job names.
This PR changes the allowed strings for `blockedBy`.
Before: `<jobName>` and `~sd@<pipelineId>:<jobName>`
After: `~<jobName>` and `~sd@<pipelineId>:<jobName>`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/653

fix(653): Only allow ~jobname for blockedBy

---

config/job.js
config/template.js
models/template.js
test/data/template.yaml

The template config directive `images` is template-specific and should not be part of the job config.  Therefore it should be relocated to the root of the template config.
* Issue: https://github.com/screwdriver-cd/screwdriver/issues/1040

fix(1040): relocate images from job config to root of template config

---

config/base.js
models/event.js
models/pipeline.js
test/config/base.test.js
test/data/config.base.config.yaml
test/data/config.base.scmUrls.yaml
test/data/event.create.full.yaml
test/data/pipeline.get.yaml

**Update 5/30**
Add `configPipelineSha` field to the events model. 
---
**Update 5/29**
Replace `isConfigPipeline` field with `scmUrls`.
---
Add optional fields `configPipelineId` and `isConfigPipeline` to the pipeline model to distinguish between **config**, **child**, and **regular** pipelines (unsure how to officially name each of these types of pipelines).
`configPipelineId` is the id of the pipeline that contains the configuration for this pipeline. This field will only be populated for child pipelines.
`isConfigPipeline` is true if the pipeline is a config pipeline.
We should discuss if adding these fields is the correct approach to distinguish between different pipeline types.
---
Also add `scmUrls ` schema into the pipeline level config. …

[1] feat(937): Add config pipeline fields and scmUrl schema

---

models/template.js
models/templateTag.js

Models can't handle Joi alternatives. Hardcoding template name to a string instead.
Seeing this error when trying to run the API locally:
```
TypeError: Cannot read property 'key' of undefined
```
Related to https://github.com/screwdriver-cd/screwdriver/issues/926#issuecomment-391907638

fix: Remove Joi alternatives from template model

---

models/template.js

Getting errors from UI:
```
{"statusCode":500,"error":"Internal Server Error","message":"\"List of templates\" at position 0 fails because [\"images\" is not allowed]"}
```
Related to https://github.com/screwdriver-cd/data-schema/pull/243

fix: Allow images to be passed in template get and create

---

plugins/scm.js
test/data/scm.getBranchList.yaml
test/plugins/scm.test.js

To get pipelines, we need to get branches by scm api.  
Scm will have new function for getting pipelines and that need properties for arguments.
Add getBranchList properties which require scmUri and token.
[github branch list api](https://developer.github.com/v3/repos/branches/#list-branches)
[bitbucket branch list api](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/refs/branches)
Related to https://github.com/screwdriver-cd/screwdriver/issues/1082

feat(1082): add get branch list property

---

config/commandFormat.js
test/config/commandFormat.test.js
test/data/config.commandFormat.habitat.local.yaml
test/data/config.commandFormat.habitat.remote.yaml

Habitat artifact (e.g. `foobar.hart`) does not have own pakcage infomation (e.g. `foo/bar/1.2.3`).
We need to have both package infomation and artifact path for habitat local mode.
Add `file` property to `command.habitat` schema which is required when `command.habitat.mode` is local.
https://github.com/screwdriver-cd/sd-cmd/pull/22#discussion_r191665209
https://github.com/screwdriver-cd/screwdriver/issues/677

feat(677): modify command.habitat schema

---

config/regex.js
test/config/regex.test.js

To check commit trigger or not. This will be used at [here](https://github.com/screwdriver-cd/models/blob/master/lib/eventFactory.js#L24).
Add COMMIT_TRIGGER regex.
Related to screwdriver-cd/screwdriver#1082

feat(1082): add commit trigger regex

---

api/validator.js
test/api/validator.test.js
test/data/validator-with-scmUrls.output.yaml

The validator output schema does not contain `SCHEMA_SCM_URLS`. This will cause the validator endpoint to return 500s if the input contains `scmUrls`.
Add `SCHEMA_SCM_URLS` to `SCHEMA_OUTPUT` in the validator
https://github.com/screwdriver-cd/screwdriver/issues/937

fix(937): Add scmUrls to validator output schema

---

models/token.js
test/data/token.invalid.yaml
test/data/token.pipeline.yaml
test/models/token.test.js

To implement pipeline API token.
I added `pipelineId` to token model.
`pipelineId` is used to indicate which pipeline the token belongs to.
`userId` and `pipelineId` is alternative keys.
token model is currently used as user token, and the token model has a `userId` to indicate which user it belongs to, but this is not required. So we can determine the role of the token depending on whether token has `userId` or `pipelineId`. It doesn't break compatibility with currently used user tokens.
proposal: https://github.com/screwdriver-cd/screwdriver/issues/614

feat(614): [1] add pipelineId to token model

---

plugins/scm.js

To use scm functions, need to send scmContext to [scm router](https://github.com/screwdriver-cd/scm-router/blob/master/index.js#L124)
Add scmContext.
[scm router](https://github.com/screwdriver-cd/scm-router/blob/master/index.js#L124)
Related to https://github.com/screwdriver-cd/screwdriver/issues/1082

fix(1082): [3] add scmContext

---

api/validator.js
config/base.js
models/pipeline.js
test/api/validator.test.js
test/config/base.test.js
test/data/config.base.childPipelines.yaml
test/data/config.base.config.yaml
test/data/config.base.scmUrls.yaml
test/data/pipeline.get.yaml
test/data/validator-with-childPipelines.output.yaml

Beyond just listing `scmUrls` we want to enable additional configuration within the `screwdriver.yaml` for  config pipelines. For instance, we want to include a `startAll` flag to determine whether to start all child pipelines whenever  the config pipeline starts.
Encompass `scmUrls` and `startAll` into an object named `childPipelines`.
https://github.com/screwdriver-cd/screwdriver/issues/937

fix(937): Add startAll flag and scmUrls to childPipelines object

---

config/job.js
config/regex.js
test/config/job.test.js
test/data/config.job.jobv2.badCommitBrRegex.yaml

SCM Branch-specific jobs
This PR adds  regex validation of commit branch filter (e.g. `/^user-.*$/`).
- [Design PR](https://github.com/screwdriver-cd/screwdriver/pull/1092)
- https://github.com/screwdriver-cd/screwdriver/issues/1082

fix(1082): [6] add regex validation of commit branch filter.

---

models/command.js
models/commandTag.js
models/template.js
models/templateTag.js
package.json
test/data/command.get.yaml
test/data/template.get.yaml

Add createTime to templates, commands, and tags so we can show when a version was published
Related to https://github.com/screwdriver-cd/screwdriver/issues/1090

fix(1090): Add createTime to templates, commands, and tags [1]

---

plugins/scm.js

When specific branch jobs are triggered, we have to clone from the branch.
Allow to send commitBranch to getCheckoutCommand.
Related to screwdriver-cd/screwdriver#1082

feat(1082): [7] allow set commit branch

---

models/token.js
test/data/token.invalid.yaml
test/data/token.pipeline.yaml
test/models/token.test.js

To implement pipeline API token.
It is almost same changes as https://github.com/screwdriver-cd/data-schema/pull/250 which we reverted last time.
Before making this change I had to modify the API side. It's merged in [this PR](https://github.com/screwdriver-cd/screwdriver/pull/1107).
So I want to revert this again.
This PR conains a [new commit](https://github.com/screwdriver-cd/data-schema/pull/257/commits/fa4f9c1b3e293a71dbb881b68fdef1d22ca5060d) to add index for `pipelineId` from [original PR](https://github.com/screwdriver-cd/data-schema/pull/250).
https://github.com/screwdriver-cd/screwdriver/issues/614

feat(614): [1] Revert 252 revert 250 pipeline token

---

models/build.js

Adding this status for builds that are blocked
Related: 
- https://github.com/screwdriver-cd/screwdriver/issues/653
- https://github.com/screwdriver-cd/screwdriver/issues/1122

fix: Add BLOCKED and UNSTABLE statuses

---

models/build.js
models/event.js
test/data/build.create.full.yaml
test/data/event.create.full.yaml
test/models/build.test.js

Allow user to pass in `meta` when creating an `event` or `build`.
Make `meta` an optional parameter for the `create` schema of `event` and `build`.
https://github.com/screwdriver-cd/screwdriver/issues/1113

feat(1113): Add meta as optional field to create builds and events

---

plugins/scm.js
test/data/scm.getCheckoutCommand.yaml

In order for an `scm` to clone the parent repository of a child pipeline, it must have information on the parent pipeline. 
This configuration will be used by `getSetupCommand` of `scm-base`.
Include `PARENT_CONFIG` schema in `GET_CHECKOUT_COMMAND`.
https://github.com/screwdriver-cd/screwdriver/issues/1132

feat(1132): Add parent config schema to getCheckoutCommand

---

config/job.js
test/config/job.test.js
test/data/config.job.jobv2.externalrequires.bad.yaml

Previously, if it fails all checks, config-parser will give:
```
"command": "echo \"TypeError: Cannot read property '3' of null\"; exit 1"
"name": "config-parse-error"
```
Now, with this change, it will give:
```
"command": "echo \"ValidationError: child \"jobs\" fails because [child \"test-or\" fails because [child \"requires\" fails because [\"requires\" at position 2 fails because [\"2\" with value \"~sd@123main\" fails to match the required pattern: /^~([\\w-]+)$/, \"2\" with value \"~sd@123main\" fails to match the required pattern: /^[\\w-]+$/, \"2\" with value \"~sd@123main\" fails to match the required pattern: /^~(sd@\\d+:[\\w-]+|pr|commit(:(.+))?)$/, \"2\" invalid trigger format], \"requires\" must be a string, \"requires\" must be a string, \"requires\" must be a string]]]\"; …
```

fix: fix error message for external trigger

---

api/loglines.js
models/build.js
test/data/loglines.query.yaml
test/data/step.get.yaml
test/data/step.update.yaml

Also change step value `pages` to `lines`
Related to https://github.com/screwdriver-cd/screwdriver/issues/1114

fix(1114): Allow loglines to have sort query

---

api/pagination.js
test/api/pagination.test.js

The pipeline events page takes a long time to load because we don't have actual pagination. We want to add pagination for getting pipeline events but remove it everywhere else (since the UI doesn't know how to handle pagination for other `list` calls).
This PR removes pagination default values for `page` and `count`;
Issue: https://github.com/screwdriver-cd/screwdriver/issues/1204

feat(1204): Remove default page and count for pagination [1]

---

plugins/datastore.js

Currently seeing this error in beta.cd.screwdriver.cd: 
```
"child "paginate" fails because ["paginate" is required]"
```
Since we're actually implementing pagination in datastore-sequelize and most calls do not actually expect pagination, we need to make the `paginate` field optional for datastore scans.
Where we're using this schema: https://github.com/screwdriver-cd/datastore-base/blob/master/index.js#L107
Related to https://github.com/screwdriver-cd/screwdriver/issues/1204

fix(1204): Make paginate field optional

---

plugins/scm.js
test/data/scm.decorateUrlWithScmInfo.yaml
test/data/scm.getFileWithScmInfo.yaml
test/plugins/scm.test.js

I found that there are 9 or more `lookupScmUri` calls in models during a single PR event even if it is rarely changed by renaming a repository or switching branches. It should be cached in each pipeline instance.
I added an optional `scmInfo` schema to `getFile` and `decorateUrl` function to accept cached scmInfo object provided by pipeline model.
It doesn't change current behavior because of optional keys.
screwdriver-cd/screwdriver#1220

[1] fix(1220): Add scmInfo to scm module functions

---

api/pagination.js
plugins/datastore.js
test/data/pagination.yaml

Users should be able to specify which field they want to sort by when queries are returned from the DB.
This PR adds a `sortBy` field to the datastore and pagination schemas. It can be any string, default will be set in the datastore to `id`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/880

fix(880): Add sortBy field [1]

---

api/pagination.js
plugins/datastore.js
test/data/pagination.yaml

Should allow upper and lowercase letters for `sortBy` (eg: `scmRepo.name`)
Related to https://github.com/screwdriver-cd/screwdriver/issues/880

fix(880): Allow uppercase in sortBy [1]

---

models/build.js
test/data/build.update.optional.yaml
test/models/build.test.js

We added a function to update build status message in executors but that is not allowed currently. Make status optional to allow that.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/757

fix(757): allow only update statusMessage

---

models/build.js

otherwise when we try to update the statusMessage by itself, it will set the status as QUEUED and try to update that too.
When we create the build we have the initial status value already: https://github.com/screwdriver-cd/models/blob/master/lib/buildFactory.js#L193

fix: remove the default build status value

---

core/scm.js
models/pipeline.js
package.json
test/data/pipeline.get.yaml

It's hard to do operations in the UI based on the pipeline name when it is stored in a JSON string in the DB under `scmRepo`.
This PR adds a pipeline `name` field at the root level of a pipeline.
Related to https://github.com/screwdriver-cd/screwdriver/issues/880

fix(880): Add optional pipeline name

---

plugins/datastore.js
test/data/datastore.search.multipleFields.yaml
test/plugins/datastore.test.js

There are many improvements to be made on the templates/commands pages. It would be nice if we had built-in search capabilities. 
The redesign would allow users to search by keyword such as `nodejs` through all template `name`, `namespace`, and `description` fields. This requires datastore support (multiple field search).
This PR adds support for multiple field search queries.
Example:
```
{
search: {
field: ['namespace', 'name', 'description'],
keyword: '%nodejs%'
}
}
```
Returns all results with "nodejs" in the `namespace`, `name`, or `description`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1271

fix(1271): Allow multiple search fields

---

plugins/scm.js
test/data/scm.getOrgPermissions.yaml
test/plugins/scm.test.js

add validation schema for getOrgPermission
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1319

fix(1319): add validation schema for getOrgPermission

---

models/buildCluster.js
test/data/buildCluster.create.full.yaml
test/data/buildCluster.get.yaml
test/data/buildCluster.update.yaml
test/data/buildCluster.yaml

add weightage to buildCluster based on the new design https://github.com/screwdriver-cd/screwdriver/pull/1357
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1319

fix(1319): add weightage to buildCluster

---

plugins/executor.js
test/data/executor.start.yaml
test/data/executor.stop.yaml

allow optional buildClusterName in executor.start 
https://github.com/screwdriver-cd/screwdriver/issues/1319

fix(1319): allow buildClusterName in executor.start

---

models/banner.js
models/buildCluster.js

- these default values will be auto apply even when users try to update other fields.
- and for create, we have logic to set the default in models already:
https://github.com/screwdriver-cd/models/blob/master/lib/bannerFactory.js#L38
https://github.com/screwdriver-cd/models/blob/master/lib/buildClusterFactory.js#L41

fix: remove default values from buildcluster and banner

---

config/job.js
config/template.js
models/template.js
test/config/job.test.js
test/data/config.job.steps.bad.yaml
test/data/template.createWithDupSteps.yaml
test/data/template.getWithDupSteps.yaml
test/models/template.test.js

The previous [PR](https://github.com/screwdriver-cd/data-schema/pull/293) enforce no duplicates steps on all the schema which breaks some current templates with duplicate steps.
This PR will allow duplicate steps for `GET` schema(list also use this), and only enforce it for `CREATE` for backward compatibility. 
References:
https://github.com/screwdriver-cd/screwdriver/issues/1317

fix(1317): allow duplicate steps for get templates

---

models/build.js
plugins/executor.js
test/data/build.create.yaml
test/data/build.get.yaml
test/data/build.update.yaml
test/data/executor.start.yaml

Allow optional build field in executor start and add stats to build model
Related: https://github.com/screwdriver-cd/screwdriver/issues/1270

[1] feat(1270): add stats to build model

---

models/job.js
package.json
test/data/job.state.get.yaml
test/data/job.state.update.yaml
test/models/job.test.js

Users want to know when why and by whom their job was disabled/enabled.
This PR adds fields for more information about job state.
_Note: not sure if there are better names for these fields._
`stateChangedBy`?
Related to https://github.com/screwdriver-cd/screwdriver/issues/1432

fix(1432): Add job disable meta fields

---

config/base.js
config/job.js
config/workflowGraph.js
models/job.js
test/config/base.test.js
test/data/config.base.jobs.badJobName.yaml

Users like to have long job names to make them more descriptive.
This PR increase the job name max length.
_Note: Not sure if this is necessary. The right solution might be to encourage use of job `description` field instead. It already exists, it just is not used or shown in the UI._

fix: Increase job name max length, add job name length validation to config parser

---

core/scm.js
test/data/scm.hook.pr.yaml

We want to add pr title to the event for using it in notification.
Add prTitle to `SCHEMA_HOOK`.
Related PRs:
models https://github.com/screwdriver-cd/models/pull/321
scm-github https://github.com/screwdriver-cd/scm-github/pull/120
screwdriver https://github.com/screwdriver-cd/screwdriver/pull/1456

[1] feat: Add pr title to the event

---

models/build.js
test/data/build.get.yaml

Adding `blockedStartTime` to build stats to track gap of time between time when build is enqueued and when it starts running.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1460

fix(1460): Add build blocked start time [1]

---

plugins/datastore.js
test/data/datastore.startTime.yaml
test/plugins/datastore.test.js

Need to allow startTime and endTime in scan schema
Related: https://github.com/screwdriver-cd/screwdriver/issues/1412

fix(1412): allow startTime endTime in scan

---

plugins/executor.js
test/data/executor.start.yaml
test/helper.js
test/plugins/executor.test.js

https://github.com/screwdriver-cd/executor-queue/pull/40 pulls in changes to executor-queue and the new start() function has additional parameters for freeze windows.
This PR updates the schema to accommodate for changes to executor.start() parameters.

fix: Update executor.start schema

---

plugins/datastore.js
test/data/datastore.groupBy.yaml

Need to allow this for step metrics: https://github.com/screwdriver-cd/models/blob/master/lib/build.js#L302
Related: https://github.com/screwdriver-cd/screwdriver/issues/1412

fix(1412): allow timeKey in scan

---

config/regex.js
core/scm.js
package.json
test/config/regex.test.js
test/core/scm.test.js
test/data/scm.hook.release.yaml
test/data/scm.hook.tag.yaml

This PR allows to use `~release` and `~tag` as a trigger.
- `release` event name is `release`
- https://developer.github.com/v3/activity/events/types/#releaseevent
- `tag` event name is `create`
- https://developer.github.com/v3/activity/events/types/#createevent
- A creating branch event is also `create` so we need filtering in the parse phase
Related: https://github.com/screwdriver-cd/screwdriver/issues/823

feat(823): [1] add ~release and ~tag trigger

---

core/scm.js
plugins/scm.js
test/data/scm.getCommitRefSha.yaml
test/data/scm.hook.pr.yaml
test/data/scm.hook.push.yaml
test/data/scm.hook.release.yaml
test/data/scm.hook.tag.yaml
test/plugins/scm.test.js

This PR fixes these:
- https://github.com/screwdriver-cd/data-schema/commit/1c801112fe395aba2829dcbd9c31f37831d8f2b0 , https://github.com/screwdriver-cd/data-schema/pull/322/commits/a8932bc08d68f50f8083f94b00cb996a2d6d65af : `action` allows to use `tag` instead of `create`
- Webhooks which are posted by release or tag do not include `sha` information.
- And we cannot have any token in `parseHooks()` phase so we cannot obtain sha information via SCM API.
- This PR allows that `sha` is empty when a release or a tag event is posted.
- https://github.com/screwdriver-cd/data-schema/commit/37ebfb66a90ca29d8bb1461dde06be0945850f35 : add ref to SCHEMA_HOOK
- `ref` will be used after `parseHook()` to get `sha` information in `getCommitRefSha()`
- …

fix(823): [1] fix release trigger related schemas

---

models/event.js
test/data/event.create.pr.yaml
test/data/event.get.pr.yaml
test/models/event.test.js

We have to get all the events including which is not PR or have other PR number, because there are no way to get exact event list with pr number in API.
Add `prNum` to the event model in order to search with pr number. 
other PR: 
[2] models: https://github.com/screwdriver-cd/models/pull/348
[3] api: https://github.com/screwdriver-cd/screwdriver/pull/1550
Issue: https://github.com/screwdriver-cd/screwdriver/issues/1010

feat(1010): [1] add prNum to event model.

---

core/scm.js
models/event.js
test/data/event.create.full.yaml

When an event is started by a periodic build, it can be hard for users to know if the build was started manually by a user, through a commit, or by Screwdriver automatically.
This PR allows `creator` to be passed into event create. Since `creator` has some extra urls that the scheduler will not have information for, this PR also makes `url` and `avatar` links optional.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1058

fix(1058): Allow creator to be passed into event create (1)

---

models/pipeline.js

Now there are orthographical variants like 'prChain' and 'chainPR' .
We want to unify these to `chainPR`.
Add `chainPR` setter/getter method to pipeline model in order to convert the `prChain` to `chainPR`.
We don't change `prChain` property itself because it is already used in data-schema and it takes too much cost to change this.
https://github.com/screwdriver-cd/workflow-parser/pull/21
https://github.com/screwdriver-cd/models/pull/371
https://github.com/screwdriver-cd/screwdriver/pull/1593

fix: [1] convert prChain to chainPR

---

core/scm.js

For a commit, author and committer may not be the same person. Add an optional field to record the committer.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1437

fix: add an optional committer field to commit

---

config/command.js

Increase max length of command usage message to 4096 characters
Related to https://github.com/screwdriver-cd/screwdriver/issues/1596

fix(1596): Increase max length of command usage

---

config/regex.js
core/scm.js
models/pipeline.js
plugins/scm.js
test/config/regex.test.js
test/data/pipeline.create.yaml
test/data/pipeline.get.yaml
test/data/pipeline.update.yaml
test/data/scm.decorateUrlWithScmRepo.yaml
test/data/scm.getCheckoutCommand.yaml
test/data/scm.parseUrl.yaml

Would be nice if users could put screwdriver.yaml not at root.
This PR adds `rootDir` to pipeline create/update, `scmRepo`, and scm method `parseUrl`
Related to https://github.com/screwdriver-cd/screwdriver/issues/1455

feat(1455): Add rootDir for pipeline create and update (1)

---

config/job.js
test/config/job.test.js
test/data/build.get.yaml
test/data/config.job.environment.array.yaml

Allow `environment` to be an array
Related: https://github.com/screwdriver-cd/screwdriver/issues/1070

fix(1070): allow environment to be an array

---

config/regex.js
test/config/regex.test.js

To achieve [this PR](https://github.com/screwdriver-cd/screwdriver/pull/1621) in API, we need to define `CORE_TRIGGERS` and `EXTRA_TRIGGERS`.
`CORE_TRIGGERS` -> triggers which can make empty events
`EXTRA_TRIGGERS` -> triggers which cannot make empty events
This time we don't use `CORE_TRIGGERS` but we defined for future.
https://github.com/screwdriver-cd/screwdriver/issues/823#issuecomment-489999734
[2] https://github.com/screwdriver-cd/screwdriver/pull/1621

fix(823): [1] add core/extra triggers regex

---

core/scm.js
test/data/scm.hook.release.yaml

SD can execute release/tag trigger, but it can't provide release/tag info(ex. name).
SD user want to get release/tag info.
Add some release fields to SCHEMA_HOOK.
Please see reference to confirm details.
https://github.com/screwdriver-cd/screwdriver/issues/823#issuecomment-490014132

fix(823): [1] Add some release fields for SCHEMA_HOOK

---

core/scm.js

**Issue #, if available:** https://github.com/screwdriver-cd/screwdriver/issues/1646
To fix this bug, it needs base branch info for pull requests.
**Description of changes:**
This PR adds `baseBranch` field for pr schema in scm.
I confirm that this contribution is made under the terms of your choice and that I have the authority necessary to make this contribution on behalf of its copyright owner.

fix(1646): [1] add baseBranch to core.scm.pr

---

models/command.js
models/template.js
test/data/command.get.yaml
test/data/template.get.yaml

To mark certain template and command as trusted, we need to modify the existing schema to include additional column on the db table
add `trusted` column to template's and command's schema
https://github.com/screwdriver-cd/screwdriver/issues/1427

fix: add "trusted" column to template and command

---

config/regex.js
package.json
test/config/regex.test.js

There seems to be no reason we can't allow to use dot for template tag name.
Allow template tag name to use dot
https://github.com/screwdriver-cd/data-schema/pull/342

fix: allow template tag name to use dot

---

plugins/scm.js
test/data/scm.getCommitRefSha.yaml

`getCommitRefSha` function can't get `sha` correctly when tag name and branch name are same.
This PR adds `refType` param so that you can distinguish
[scm_github PR](https://github.com/screwdriver-cd/scm-github/pull/138)

fix: [1] add refType param in getCommitRefSha

---

models/job.js
models/trigger.js
test/models/job.test.js
test/models/trigger.test.js

Improve DB query performance by using an index scan
Added index based on the data access pattern from the database metrics
pipelineId and state columns used in where clause query of the jobs table will fire a single index scan

fix: add index

---

core/scm.js
test/core/scm.test.js
test/data/scm.hook.push.invalid-array.yaml
test/data/scm.hook.push.invalid-commiters.yaml

Currently there's a mismatch in v3 and v4 ci skip logic. To change v4 ci skip logic to match v3 we need an additional field.
This PR add an optional field to hook schema
https://github.com/screwdriver-cd/screwdriver/issues/1747

fix(1747): adding commit authors to hook schema

---

models/event.js
test/data/event.create.full.yaml

To use branch info in the restarted build and triggered build, I added branch info to event schema.
Add branch info to event schema.
https://github.com/screwdriver-cd/screwdriver/issues/1755
https://github.com/screwdriver-cd/screwdriver/issues/1760
Related PRs:
https://github.com/screwdriver-cd/models/pull/396
https://github.com/screwdriver-cd/scm-base/pull/72
https://github.com/screwdriver-cd/screwdriver/pull/1770

[1] fix(1755): Add branch info to event schema

---

package.json
plugins/executor.js
test/data/executor.start.yaml

Sometimes users want to override their freeze window quickly without changing the screwdriver.yaml.
This PR adds a field `causeMessage` to executor start. Users can pass in `[force start]` keywords (similar to [skip ci]) to force a build to start during a freeze window.
_Note: Not sure if `force start` is the best keyword phrase. Open to other ideas: `override frozen`, `ci` (as the opposite of `skip ci`?), etc._
Related to https://github.com/screwdriver-cd/screwdriver/issues/1675

fix(1675): Add causeMessage to executor start [1]

---

models/event.js

Sometimes causeMessage is not set.
This PR allows empty string for causeMessage.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1675

fix: Allow empty string for causeMessage

---

migrations/20190919-initdb-banners.js
migrations/20190919-initdb-buildClusters.js
migrations/20190919-initdb-builds.js
migrations/20190919-initdb-collections.js
migrations/20190919-initdb-commandTags.js
migrations/20190919-initdb-commands.js
migrations/20190919-initdb-events.js
migrations/20190919-initdb-jobs.js
migrations/20190919-initdb-pipelines.js
migrations/20190919-initdb-secrets.js
migrations/20190919-initdb-steps.js
migrations/20190919-initdb-templateTags.js
migrations/20190919-initdb-templates.js
migrations/20190919-initdb-tokens.js
migrations/20190919-initdb-triggers.js
migrations/20190919-initdb-users.js
migrations/20191111-add_uniquekey_to_collections.js
migrations/20191111-add_uniquekey_to_commandTags.js
migrations/20191111-add_uniquekey_to_commands.js

sequelize-cli migration files are 1. missing unique keys in collections, commands, commandTags tables and 2. ID column in MySQL is int(11) instead of int(10) unsigned 
This PR addresses missing unique keys in collections, commands, commandTags tables, and ID column type change from Integer to Integer.UNSIGNED for MySQL
[1824](https://github.com/screwdriver-cd/screwdriver/issues/1824)

fix(1824): add missing unique keys and update id column type

---

config/job.js

Currently the filename limit for SourcePath is set to 100 and thus validation fails when we try to use a filename which is greater than 100 characters.  Requesting an increase to 1024 characters.
PR fixes the filename character limit

fix: increasing SourcePath char limit to 1024

---

migrations/20191214-rename_scmContext-buildClusters.js
models/buildCluster.js
test/data/buildCluster.create.full.yaml
test/data/buildCluster.create.yaml
test/data/buildCluster.get.yaml
test/data/buildCluster.yaml

Build cluster supports only one SCM context, which leads to error "This pipeline is not authorized to use this build cluster." if the same build cluster is used for different SCM context.
This PR is intended for a build cluster to support multiple SCM contexts
[1881](https://github.com/screwdriver-cd/screwdriver/issues/1881)

feat(1881): build cluster to support multple scm conexts

---

migrations/20191217-upd_buildCluster_uniquerow.js
models/buildCluster.js
test/models/buildCluster.test.js

Build cluster supports only one SCM context, which leads to error "This pipeline is not authorized to use this build cluster." if the same build cluster is used for different SCM context.
This PR updates the unique constraint from name to a combination of name and scmContext. Random active build cluster assignment will be based on the combination of name and scmContext.
[1881](https://github.com/screwdriver-cd/screwdriver/issues/1881)

fix(1881): build cluster to support multiple scm contexts

---

plugins/executor.js

Add enqueueTime to get the time when build was pushed to queue
This field will be used for comparing runtime of build with timeout
https://github.com/screwdriver-cd/screwdriver/issues/1839

fix(1839): Add enqueueTime to start schema

---

README.md

Screwdriver api failing to start with key null error. Locally it works as expected, but on the server, it fails.
Reverting build cluster multiple scmContexts changes to see if that addresses the issue
[1881](https://github.com/screwdriver-cd/screwdriver/issues/1881)

fix(1881): revert build cluster multiple scmcontext changes

---

migrations/20191221-add-column-builds-parentBuilds.js
migrations/20191221-upd-buildClusters-uniqueconstraint.js
models/buildCluster.js
test/data/build.yaml
test/models/buildCluster.test.js

Build cluster supports only one SCM context, which leads to error "This pipeline is not authorized to use this build cluster." if the same build cluster is used for different SCM context.
parentBuilds column missing in builds migrations file
This PR updates the unique constraint from name to a combination of name and scmContext. Random active build cluster assignment will be based on the combination of name and scmContext. Add parentBuilds column to the builds migration file.
[1881](https://github.com/screwdriver-cd/screwdriver/issues/1881)
[1710](https://github.com/screwdriver-cd/screwdriver/issues/1710)
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …

fix(1881): add scmContext constraint and fix #1710

---

config/job.js
config/workflowGraph.js
test/data/config.workflowGraph.yaml

Workflow graph should allow dest that look like external triggers (ie: `sd@123:main`).
This PR allows external triggers for src/dest in workflow graph.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1710

fix(1710): Update workflowGraph to allow external join trigger

---

models/build.js
test/data/build.get.yaml

When adding default parentBuilds values, we put `null` in the place of IDs (https://github.com/screwdriver-cd/screwdriver/blob/06eb9ddf80495edc74f44e3261c65e6546d8b81c/plugins/builds/index.js#L409-L413). This is currently causing external parallel fork join builds to fail with this error:
```
[request,server,error] data: Error: "List of builds" at position 0 fails because [child "parentBuilds" fails because [child "1093" fails because [child "eventId" fails because ["eventId" must be a number]]]]
```
This PR allows null for parentBuilds IDs.
Fix: https://github.com/hapijs/joi/issues/504
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1710
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree …

fix(1710): Allow null for parentBuilds ids

---

models/build.js

Does not seem possible to add `.allow(null)` to a `Joi.number()`.
This PR changes the ID to allow for number or null.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1710

fix: Allow null or number for id in parentBuilds

---

config/job.js
config/regex.js
models/event.js
test/data/event.create.restart.yaml

When restarting a build, it would be nice to see parentBuilds information.
This PR allows passing in parentBuilds info to event create so it can be passed into build create.
This PR also adds regex for OR and AND case for external trigger.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1710

fix(1710): Allow pass in parentBuilds to event create [1]

---

migrations/20200114-del-column-builds-steps.js
models/build.js
test/data/build.get.yaml
test/data/build.yaml

As mentioned here screwdriver-cd/screwdriver#1865 , builds.steps and steps.command are both same data.
And these steps are defined by user's yaml and it tends to have a big size.
Create migration file which removes steps column in builds table, because we fixed not to use steps column.
- https://github.com/screwdriver-cd/models/pull/423
- https://github.com/screwdriver-cd/screwdriver/issues/1865

fix(1865): [3] Remove steps column in builds table

---

migrations/20200203-add-column_templateId_to_jobs.js
migrations/20200204-add-column_templateId_to_builds.js
models/build.js
models/job.js
plugins/datastore.js
test/data/datastore.aggregationField.yaml
test/models/build.test.js
test/models/index.test.js
test/models/job.test.js
test/plugins/datastore.test.js

Need to allow "aggregationField" in scan config so aggregation queries can be made.
This PR adds "aggregationField" to SCHEMA_SCAN so that scan configs that include aggregationField pass validation.
https://github.com/screwdriver-cd/screwdriver/issues/1091

fix(1091): add aggregation field to scan schema

---

plugins/scm.js
test/data/scm.getCheckoutCommand.yaml

I fix [issue](https://github.com/screwdriver-cd/screwdriver/issues/965).
I add new variables,`PR_BRANCH_NAME`
This PR adds `prBranchName` to the joi validator of  `GET_CHECKOUT_COMMAND`.

fix(965):[1] $GIT_BRANCH invalid value in PR builds

---

core/scm.js
test/data/scm.pr.yaml

I am fixing the following features:
[1] https://github.com/screwdriver-cd/data-schema/pull/386
[2] https://github.com/screwdriver-cd/scm-base/pull/75
[3] https://github.com/screwdriver-cd/scm-github/pull/150
[4] https://github.com/screwdriver-cd/screwdriver/pull/1980
[2] Chain PR stopped working after merge.
The reason is that the environment variables required to `BuildFactory` have not been added.
Therefore, we will modify chainPR to work.
Add necessary data when calling `BuildFactory`.

fix(965)[1]:  ChainPR does not work

---

migrations/20200304-add-column_groupEventId_to_events.js
models/event.js
test/data/event.create.full.yaml

Need a way to group similar events that we triggered by the same event or started manually.
This PR adds a new field `groupEventId` to event model to track similar events. `parentEventId` cannot be used since it tracks the direct parent event id, not the master parent event id.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1785

feat(1785): Add groupEventId [1]

---

migrations/20200316-extend-startFrom-to-events.js
models/event.js

It's important to update the field so it has the proper description in the swagger API documentation. However, `startFrom` is not required when `buildId` is provided (https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/events/create.js#L34-L52).
This PR moves the definition of `startFrom` from the CREATE_MODEL to the BASE.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2026

fix(2026): Update startFrom field [1]

---

plugins/datastore.js
test/data/datastore.query.rawResponse.yaml
test/data/datastore.query.replacements.yaml
test/data/datastore.query.yaml
test/plugins/datastore.test.js

Need to add the ability to do raw queries to datastore so queries that are otherwise impossible to do through sequelize can be done, as such need to add a schema for this method to data schema.
Add a schema for the datastore query method to data schema so method calls can be validated.
https://github.com/screwdriver-cd/screwdriver/issues/1967

feat(1967): add query to datastore

---

models/event.js
test/models/event.test.js
test/models/index.test.js

Adding `groupEventId` as a field to index to events model will help with faster lookup.
This PR adds `groupEventId` to events index.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1785

fix(1785): Add groupEventId index for events

---

config/regex.js
test/config/regex.test.js

Using dot is allowed in template/command tag.
However, it is not allowed in template/command full name regex.
It should be allowed also in template/command full name.
Allow dot in template/command full name regex.
https://github.com/screwdriver-cd/data-schema/pull/343
https://github.com/screwdriver-cd/data-schema/pull/342

fix: allow dot in template/command full name

---

config/regex.js
test/config/regex.test.js

When chainPR triggers remote join, event screen does not show full workflowgraph in pr event list.
The error message is like below.
```
200521/022434.929, (1590027874916:3d8985daec91:31:kag51fdw:10970) [request,server,error] data: Error: "List of builds" at position 0 fails because [child "parentBuilds" fails because [child "20" fails because [child "jobs" fails because ["PR-1:sd@21:external_fork" is no
t allowed, "PR-1:sd@22:external_fork" is not allowed]]]]
```
Fix validation error on chainPR with remote join. This PR makes chainPR possible to show full workflowgraph like below.
(Jobs which not executed is external things, so it is no problem on chanPR)
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree …

fix: validation error on chanPR with remote join

---

migrations/20200611-add_index_groupEventId_to_events.js

The specific query of remote join is slowly without `groupEventId` index. Therefore we need to add `groupEventId` index to events. 
Add `groupEventId` index to events. 
https://github.com/screwdriver-cd/data-schema/pull/395

fix: Add index groupEventId to events

---

config/regex.js
test/config/regex.test.js

checkoutUrl regex rejects valid url with pattern like `org-1234@github.com:/a/b.git`
change regex to accept `org-1234@github.com:/a/b.git`
https://github.com/screwdriver-cd/screwdriver/issues/2017

fix(2017): fix checkoutUrl regex

---

config/index.js
config/tokenConfig.js
plugins/executor.js
test/config/tokenConfig.test.js
test/data/config.tokenConfig.yaml
test/data/executor.start.yaml

Jwt token config used for auth needs a defined schema which will validate any changes to the token structure
This PR adds token config schema and additional properties to executor schema

fix: Add schema for jwt token config

---

migrations/20200618-add_index_parentEventId_to_events.js
models/event.js
test/models/event.test.js

The specific query of remote join is slowly without parentEventId index. 
It was not enough to add the index groupEventId.
Therefore we need to add parentEventId index to events.
Add parentEventId index to events.
#399 

fix: Add parentEventId index

---

api/validator.js
test/api/validator.test.js
test/data/validator.warningsoutput.yaml

Add feature of https://github.com/screwdriver-cd/screwdriver/issues/2053
In this PR,  allow the API to throw the array with warning annotations.
This PR is a preparation for users to be aware of Annotations that are not valid when they are set.
Add a new `warnAnnotations` to the validator's output schema.
This is part of https://github.com/screwdriver-cd/screwdriver/issues/2053
[2] https://github.com/screwdriver-cd/config-parser/pull/107

feat(2053): [1]  Add warning annotations to the validator response

---

models/pipeline.js
test/data/pipeline.update.yaml

screwdriver-cd/screwdriver#1079
Add autoDeployKeysGeneration flag to update schema.
screwdriver-cd/screwdriver#1079

fix(1079): Add autoKeysGeneration key to update schema and tests

---

config/command.js
models/banner.js
models/event.js
models/job.js
test/models/index.test.js

As it has been accidentally deleted previously, I want bringing it back with this PR.
https://github.com/screwdriver-cd/data-schema/commit/679ed5d26a7c16d44e69ecac149a37bde1007cb2#diff-f9752cf0b76dbe6ff913d5934b1fe45bL41
https://github.com/screwdriver-cd/data-schema/pull/311

fix: add key length for mysql

---

models/banner.js
models/build.js
models/buildCluster.js
models/collection.js
models/command.js
models/commandTag.js
models/event.js
models/job.js
models/pipeline.js
models/secret.js
models/step.js
models/template.js
models/templateTag.js
models/token.js
models/trigger.js
models/user.js

[Sequelize](https://github.com/screwdriver-cd/datastore-sequelize/blob/b4609dc1ccb38888b26afc2f048f5f9cec6b6bb5/index.js#L27) library uses joi.object().describe() to get all the keys that are there in the model, profiling the sd node process has showed that this heavily used function takes up a lot of the processing time due to the nature of it describe a huge joi object on the entire model which leads to performance issues. To fix this we need to expose the model object itself to sequelize.
This PR adds a property fields on models and exposes the model object.
https://github.com/screwdriver-cd/screwdriver/issues/2216
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary …

feat: expose a fields property on models

---

api/validator.js

[The test is failing](https://cd.screwdriver.cd/pipelines/1/events/510195) with the following error.
```
data: ValidationError: "subscribe" is not allowed
```
https://github.com/screwdriver-cd/screwdriver/issues/1415
Related to https://github.com/screwdriver-cd/config-parser/pull/109

fix(1415): add subscribe

---

config/settings.js
test/data/pipeline.get.yaml
test/data/pipeline.update.yaml

Would be better for UI to pass in array of job IDs rather than have the API look them up.
This PR changes `downtimeJobs` to array of `jobIds` vs `jobNames`; also adds `downtimeStatuses`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2199

fix(2199): Downtime jobs should be array of jobIds [1]

---

migrations/20201102-change_column_subscribedScmUrlsWithActions_to_pipelines.js

Migration file https://github.com/screwdriver-cd/data-schema/blob/master/migrations/20200922-add_column_subscribedScmUrlsWithActions_to_pipelines.js#L12 has the wrong type for field

fix(1415): fix the migration file

---

plugins/datastore.js
test/data/datastore.search.multipleKeywords.yaml
test/plugins/datastore.test.js

We are changing scan() to support multi keyword search, this is a change to support that
Allow keyword array
https://github.com/screwdriver-cd/screwdriver/issues/2267
https://github.com/screwdriver-cd/datastore-sequelize/pull/78

feat(2267): allow multiple keyword scan

---

migrations/20201102-change_column_subscribedScmUrlsWithActions_to_pipelines.js
models/pipeline.js

[migrations/20201102-change_column_subscribedScmUrlsWithActions_to_pipelines.js](https://github.com/kumada626/data-schema/blob/9ebe3a42d3779de62e8c371ebe06cde74de883ec/migrations/20201102-change_column_subscribedScmUrlsWithActions_to_pipelines.js) is not applied on mysql.
Because text column has to be indexed with length in mysql.
Therefore, in the case of mysql the index must be dropped before changing the column type.
Drop index before changing the column type.
Re add index after changing the column type.

fix: Fix migration file for mysql

---

api/validator.js
test/data/validator.warningsoutput.yaml

API is outputting error message `data: ValidationError: "warnMessages" is not allowed`, I fixed it.
It should work correctly when combined with the following modules.
https://github.com/screwdriver-cd/models/releases/tag/v28.5.5
https://github.com/screwdriver-cd/config-parser/releases/tag/v6.3.0
https://github.com/screwdriver-cd/screwdriver/issues/1815
[4] : https://github.com/screwdriver-cd/data-schema/pull/427 (this PR)
[5] : https://github.com/screwdriver-cd/screwdriver/pull/2308

[4]feat(1815): change to warnMessages from warnAnnotations

---

api/templateValidator.js
api/validator.js
config/job.js
test/data/config.template.yaml
test/data/template-validator.output.yaml
test/data/template.create.yaml

Would be nice if template owners could pick and choose which steps from a template should be run in their own.
This PR adds support for the `order` keyword in a job; also adds support for warnMessages for template validator.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2319

feat(2319): [1] Add order field to job config, warnMessages for template validator

---

api/pagination.js
plugins/datastore.js
test/data/datastore.search.multipleFields.yaml
test/data/paginationFull.yaml

Would be nice if we can get total count alongside paginated content
Add a field `getCount` to indicated that we want to get total count
https://github.com/screwdriver-cd/screwdriver/issues/2312

fix(2312): add getCount to pagination and scan

---

migrations/20210122-add_column_latestVersion_to_commands.js
migrations/20210122-add_column_latestVersion_to_templates.js

used wrong variable Sequelize to get dialect, should use queryInterface.sequelize.getDialect() instead
used wrong variable Sequelize to get dialect, should use queryInterface.sequelize.getDialect() instead

fix: should use queryInterface.sequelize instead

---

config/annotations.js

I added support for new annotations in the UI, so I want to add the annotation for validator.
https://github.com/screwdriver-cd/ui/pull/670
When using the `screwdriver.cd/manualStartEnabled` annotation, the validator will not output a warning.
https://github.com/screwdriver-cd/screwdriver/issues/1901

[2]fix(1901): add screwdriver.cd/manualStartEnabled annotation

---

config/settings.js
test/data/user.get.yaml
test/data/user.update.yaml

add to allow arbitrary keys, and add `showPRJobs` for individual pipeline settings in user settings.
* enforce pipeline settings
* update test
[Joi Tester](https://framp.me/joi-tester/)

fix: update user settings

---

api/validator.js
test/data/job.yaml

Would be nice if the UI could show locked steps in a job when template is used.
This PR allows more data to be sent from config parser through commands so locked step can be shown in the UI.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2331

fix(2331): Pass locked job steps [2.5]

---

config/job.js

Template tag is failing with:
```
00:00:10 $ template-tag --name tiff/template --tag latest
00:00:10 Error: Error getting latest template version. 500 (Internal Server Error): "[0].config.templateId" is not allowed
00:00:10     at request.then (/usr/local/lib/node_modules/screwdriver-template-main/index.js:158:19)
00:00:10     at <anonymous>
00:00:10     at process._tickCallback (internal/process/next_tick.js:189:7)
```
https://cd.screwdriver.cd/pipelines/256/builds/682810/steps/autotag
This PR adds `templateId` field to template `config` section.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2331
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to …

fix(2331): Add templateId to template config

---

config/template.js

Template config should be allowed to just have a `template` without `image` and `steps`.
Currently, the validator is failing with this template yaml:
```
name: test
namespace: demo
version: "1.0"
maintainer: foo@bar.com
description: Demo locked step
config:
image: node:8
template: tifftemplate@1.0.2
```
With these errors:
```
"image" missing required peer "steps"
"config" must contain at least one of [steps]
```
This PR just checks that either template is present or both image and steps.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2331

fix(2331): Allow only template for template config

---

config/regex.js
test/config/regex.test.js
test/data/config.base.childPipelines.yaml

Would be nice if external config users could specify source dir not at checkout root.
This PR adds the option to have `rootDir` on the end of `checkoutUrl`, separated by `:`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2398

fix(2398): Add rootDir to checkoutUrl regex [1]

---

models/job.js
package.json
test/data/job.state.update.yaml

Currently, users can pass in `stateChanger` and `stateChangeTime` to job update endpoint. This information does not need to be passed in, since we can gather it from user credentials, etc.
This PR removes `stateChanger` and `stateChangeTime` from allowed job update params.
Note: This will break anyone directly calling `PUT /jobs/:id` with `stateChanger` and `stateChangeTime` passed in.
Blocked by https://github.com/screwdriver-cd/screwdriver/pull/2412
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

fix: Do not allow stateChanger and stateChangeTime in job update [3]

---

models/buildCluster.js
test/data/buildCluster.create.yaml
test/data/buildCluster.update.yaml

Should be allowed to pass in scmContext to build cluster. This is necessary for read-only SCM, since scmContext cannot be derived from user profile (since you cannot login to read-only SCM).
This PR allows scmContext to be passed into build cluster create/update. 
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437, https://github.com/screwdriver-cd/screwdriver/pull/2495

fix(2437): Allow passing in scmContext to buildCluster [1]

---

migrations/20210310-add_uniquekey_to_builds.js

Under the mysql environment, the following error occurred during migration, so fix it.
```
ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to us
e near '"builds" AS a, "builds" AS b WHERE a.id > b.id AND a."eventId" = b."eventId" AND' at line 1
```
Migration become possible under mysql environment.

fix: migration error for mysql

---

models/pipeline.js

It's confusing what certain fields are for in the API.
This PR adds a description to the field autoKeysGeneration.
N/A

fix: Add description to autoKeysGeneration

---

migrations/20211004-update_trigger_length-triggers.js
models/trigger.js

The [max job name length](https://github.com/screwdriver-cd/data-schema/blob/master/config/job.js#L81) is 100 chars, but the [max trigger name length](https://github.com/screwdriver-cd/data-schema/blob/master/models/trigger.js#L12-L31) is only 64 chars (including the additional `~sd@` prefix).
This PR bumps up the max trigger name length to 128. 
N/A

fix: Bump up max char length for triggers

---

plugins/executor.js

Should not fail if extra params are passed into executor.
This PR adds allowUnknown to executor params.
N/A

fix: Allow other fields for executor params

---

plugins/executor.js
test/data/executor.stop.yaml

`jobname` and `apiUri` are needed in executor stop config for AWS Integration
This PR adds jobname and apiUri in executor stop config
https://github.com/screwdriver-cd/screwdriver/issues/2559
https://github.com/screwdriver-cd/screwdriver/issues/2561

feat(#2561): Add jobname & apiuri to executor stop config

---

config/template.js
migrations/20211215-add_column_parameters_to_templates.js
models/template.js
test/config/template.test.js
test/data/config.template.parameters.yaml

Parameters can be defined only in Screwdriver pipeline configuration and but not in templates.
Provide a way to define parameters in sdv4 template so not everyone needs to add it when they use the sdv4 template.
https://github.com/screwdriver-cd/screwdriver/issues/2624

feat(2624): Support to define parameters in SDV4 templates

---

core/scm.js
plugins/scm.js
test/core/scm.test.js
test/data/scm.getChangedFilesInput.yaml
test/data/scm.hook.push.invalid-added-files.yaml
test/data/scm.hook.push.invalid-modified-files.yaml
test/data/scm.hook.push.invalid-removed-files.yaml

To support the changes in https://github.com/screwdriver-cd/scm-github/pull/200, I change the data structure associated with SCM.
- Add property(addFiles, modifiedFiles, removedFiles) to SCHEMA_HOOK.
- Change property name of GET_CHANGED_FILES_INPUT.
[scm-base PR](https://github.com/screwdriver-cd/scm-base/pull/90)
[scm-github PR](https://github.com/screwdriver-cd/scm-github/pull/200)
[scm-gitlab PR](https://github.com/screwdriver-cd/scm-gitlab/pull/49)
[screwdriver PR](https://github.com/screwdriver-cd/screwdriver/pull/2622)
https://github.com/screwdriver-cd/screwdriver/issues/1769#issuecomment-934107626
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …

feat(1769): [1] Add property to SCHEMA_HOOK

---

package.json

We're on a fairly old version of cron-parser; latest version has support for "run on the last weekday of the month".
This PR updates to use latest version of cron-parser package: https://www.npmjs.com/package/cron-parser
N/A

fix: Update to cron-parser v4.0

---

config/annotations.js
config/provider.js
test/data/config.job.providersls.yaml

Users should be able to opt-in to use short-lived git deploy keys for `git checkout` when running builds with Screwdriver AWS integration
This PR adds git `useDeployKey` annotation along with additional provider properties

feat: add git deployKey annotation and additional provider properties

---

migrations/20220203-uniquekey-update-events.js
models/event.js
package.json

When a single PR generates multiple events across different pipelines for same repository ([source dir](https://docs.screwdriver.cd/user-guide/configuration/sourceDirectory)), some of the event creation can fail, since `createTime` & `sha` is a unique constraint. Multiple events can get same `createTime` since it's [generated by API ](https://github.com/screwdriver-cd/models/blob/master/lib/eventFactory.js#L802)
Add pipeline Id to unique Key constraint so that event creation for multiple pipelines caused by same PR  (due to Source Dir feature) can work. 
https://github.com/screwdriver-cd/screwdriver/issues/2640
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make …

fix(2640): add pipelineId to unique key constraint

---

config/provider.js

`buildRegion` should be allowed to be empty
This PR allow empty for property `buildRegion`

feat: Add allow empty to buildRegion

---

migrations/20190919-initdb-banners.js
migrations/20190919-initdb-buildClusters.js
migrations/20190919-initdb-builds.js
migrations/20190919-initdb-collections.js
migrations/20190919-initdb-commandTags.js
migrations/20190919-initdb-commands.js
migrations/20190919-initdb-events.js
migrations/20190919-initdb-jobs.js
migrations/20190919-initdb-pipelines.js
migrations/20190919-initdb-secrets.js
migrations/20190919-initdb-steps.js
migrations/20190919-initdb-templateTags.js
migrations/20190919-initdb-templates.js
migrations/20190919-initdb-tokens.js
migrations/20190919-initdb-triggers.js
migrations/20190919-initdb-users.js
migrations/20191221-upd-buildClusters-uniqueconstraint.js

migration for new screwdriver cluster is not working due to sequelize's params change.
the error is like below:
> ERROR: Fields must be specified through options.fields
modify old migration files to current sequelize params.
it passed migration for an empty database (using MySQL 5.7.33).
- [QueryInterface | Sequelize](https://sequelize.org/master/class/src/dialects/abstract/query-interface.js~QueryInterface.html#instance-method-addConstraint)

fix: modify migration files to current sequelize params

---

config/settings.js

Add ability to save the preference of filter events for no builds.
And fixed an [issue](https://github.com/screwdriver-cd/screwdriver/issues/2668) where when any of the pipeline preferences was turned on, it would be turned off except for the target setting.
UI PR is [here](https://github.com/screwdriver-cd/ui/pull/770).
- Add ability to save the preference of filter events for no builds.
- Fixed to use `optional()` instead of `default(false)`
- https://github.com/screwdriver-cd/screwdriver/issues/1577
- adding a toggle switch on a pipeline or an option page to filter empty events.
- https://github.com/screwdriver-cd/screwdriver/issues/2668
-  when any of the pipeline preferences was turned on, it would be turned off except for the target setting.
I confirm that this contribution is made …

feat(1577): add option filteredEventsForNoBuilds

---

config/job.js
package.json
plugins/executor.js
test/data/config.job.providerexternal.yaml

Users might want to point their provider to an external repo rather than copy paste a bunch of repetitive code.
This PR allows for a checkout url type string as the provider in a screwdriver.yaml.
before:
```
provider:
name: aws
region: us-west-2
accountId: 111111111111
role: arn:aws:iam::111111111111:role/role
executor: eks
clusterName: sd-build-eks
```
after:
`provider: git@github.com:tkyi/testing.git#test:provider.yaml`
Related to https://github.com/screwdriver-cd/screwdriver/issues/2676

fix(2676): Allow provider path to external repo

---

config/provider.js
test/data/config.job.providersls.yaml

The property `environment` name was incorrect, consumer service refers to `environmentType`
This PR updates the name of property to `environmentType`

fix: update property name to environmentType

---

config/annotations.js
package.json

Sometimes users might have repos/pipelines with build periodic configs. If developers fork and create their own pipelines, they might not want these cron jobs to get auto triggered. It would be nice to have an additional annotation for disabling jobs upon creation so users are required to consciously enable them if they want the periodic builds.
This PR adds a new annotation to job annotations: `screwdriver.cd/jobDisabledByDefault`.

fix: Add annotation to disable job by default [1]

---

plugins/scm.js
test/data/scm.addPrComment.yaml

In implementing https://github.com/screwdriver-cd/screwdriver/issues/2695, pipeline id and job name are needed in `addPrComment`.
We add job name and pipeline id to `scm.addPrComment`.
https://github.com/screwdriver-cd/screwdriver/issues/2695
Reflect at the same time as https://github.com/screwdriver-cd/models/pull/543

[1]feat(2695): Add jobName and pipelineId to scm.addPrComment

---

migrations/20220628180148-remove_pr_jobs_invalid_name.js

Raw queries updated in https://github.com/screwdriver-cd/models/pull/547 and https://github.com/screwdriver-cd/models/pull/548 is causing below error for certain pipelines (Ex: https://cd.screwdriver.cd/pipelines/9)
`negative substring length not allowed`
Those pipelines have pull request jobs that were created before 2018 which violates the naming format `PR-<PULL_REQUEST_NUMBER>:<PARENT_JOB_NAME>` (Ex: `PR-32:main`). Here are few invalid job names associated with https://cd.screwdriver.cd/pipelines/9
```
PR-147
PR-148
PR-149
PR-150
PR-151
```
Here are some queries (PostgreSQL) to detect pull request jobs with invalid name
**Total count**
```
SELECT COUNT(*)
FROM "jobs"
WHERE name LIKE 'PR-%'
AND POSITION(':' IN name) = 0;
```
**Job Details**
```
SELECT *
FROM "jobs"
WHERE name LIKE …
```

fix(2496): Remove PR jobs with invalid name

---

config/settings.js
test/data/user.get.yaml
test/data/user.update.yaml
test/data/user.yaml

When user looks at events, getting several events happened "2 months ago." When looking  at the list view, confused with timestamp such as "August 18, 2020 4:52 PM."
Preference is to have absolute timestamps on the events sidebar. Have a session for Event Timeline Format under the Options -> User Preference -UTC Timestamp, Local Timestamp, Human Readable Timestamp
https://github.com/screwdriver-cd/screwdriver/issues/2218

fix to have timestamps on the events sidebar

---

config/template.js
migrations/20220728171252-remove_column_parameters_from_templates.js
models/template.js
test/config/template.test.js
test/data/config.template.parameters.yaml

`parameters` column in `templates` table is not being used. `parameters` is embedded into the config which is stored under the column `config`.
This PR drops the column `parameters` from the `templates` table.
https://github.com/screwdriver-cd/screwdriver/issues/2649

fix(2649): Remove unused column 'parameters' from 'templates' table

---

migrations/20220607152947-add_column_state_to_pipeline.js
models/pipeline.js
test/data/collection.get.yaml
test/data/pipeline.get.yaml
test/data/pipeline.yaml
test/models/pipeline.test.js

Changes were made in https://github.com/screwdriver-cd/models/pull/534 to stop auto deletion of child pipelines when the SCM URLs removed/modified in the external config.
We need a way to distinguish between active and obsolete child pipeline to allow the user to review and take necessary actions on obsolete child pipelines
- reactivate the pipeline by restoring the SCM URL in the external config
- explicitly delete the pipeline from the UI/API
This PR adds a new field called `state` to the `pipeline` model to distinguish between active and obsolete child pipelines.
https://github.com/screwdriver-cd/screwdriver/issues/2580
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority …

feat(2580): Add a new field 'state' to pipeline model to distinguish between active and obsolete child pipelines

---

config/settings.js

User cannot rename the pipeline back to empty string, on changing AliasName to an empty string it gives `400`.
Users can rename the pipeline alias back to an empty string.
https://github.com/screwdriver-cd/screwdriver/issues/2744

fix: allow aliasname empty

---

models/pipeline.js

`state` field on the `pipeline` is meant to be non-nullable. It is not marked are required in the schema.
This PR marks the field are required in the schema.
https://github.com/screwdriver-cd/screwdriver/issues/2580
Related PRs:
https://github.com/screwdriver-cd/data-schema/pull/490

fix(2580): Make 'state' as required in pipeline schema

---

config/settings.js
test/data/user.get.yaml
test/data/user.update.yaml
test/data/user.yaml

Re-order timestampFormat to top level user preference
See 
Before:
After:
1. move `timestampFormat` to top level
2. remove `HUMAN_READABLE` from `timestampFormat`
https://joi.dev/api/?v=17.6.0#objectappendschema

fix: update timestampFormat

---

config/settings.js
test/data/user.get.yaml
test/data/user.update.yaml

Re-order JobNameLength to user settings.
Move JobNameLength from User Preference to user settings .

fix: Display JobNameLength in user settings

---

migrations/20220908-remove_unique_constraint_from_stages.js

After changing up the stages schema, a new unique constraint was added: https://github.com/screwdriver-cd/data-schema/blob/master/migrations/20220705-upd-stage-color-eventId-createTime.js#L27, https://github.com/screwdriver-cd/data-schema/blob/master/models/stage.js#L71
So we no longer need the old unique constraint: https://github.com/screwdriver-cd/data-schema/blob/master/migrations/20220607-initdb-stages.js#L43
This PR removes the old unique constraint through a migration file.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2669

fix(2669): Remove old unique constraint for stages table

---

models/stage.js
package.json

Should not allow empty jobs list for stage definitions.
This PR removes optional tag and allow null for jobIds.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2669

fix(2669): Do not allow empty array for stage jobIds [1]

---

config/settings.js

To add toggle to hide scheduler events.
https://github.com/screwdriver-cd/screwdriver/issues/2849

add filterSchedulerEvents field in pipeline settings

---

config/regex.js
config/template.js
test/config/regex.test.js

This change will allow for an alias such as `xcode:14.1`. Without this change the alias needs to be something unnatural such as `xcode-14_1`.
The image aliases are essentially only dictionary keys, so it's not clear why their naming need be restricted at all, much less be any more restrictive than the image name itself. However, on the assumption that there is a reason for the naming restriction, this commit take the conservative approach of adding only two additional characters.
This change will allow for an alias such as `xcode:14.1`. Without this change the alias needs to be something unnatural such as `xcode-14_1`.
Less restrict naming on image aliases.
None.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source …

Add '.', ':', to IMAGE_ALIAS regex

---

migrations/20230522124151-add-column_group_to_buildCluster.js
models/buildCluster.js
test/data/buildCluster.group.yaml
test/models/buildCluster.test.js

Logically group build cluster with default based on the environment. 
This PR adds a new column `group` to build cluster schema

feat: add group to build cluster

---

migrations/20230522124151-add-column_group_to_buildCluster.js
models/buildCluster.js

Build cluster group is restricitve
This PR updates the group field to be a string and not limit the group names

feat: make build cluster group name more relaxed

---

core/scm.js
test/data/scm.user.yaml

Follow up of PR https://github.com/screwdriver-cd/data-schema/pull/518
This PR normalize the type of SCM user id to String.
https://github.com/screwdriver-cd/screwdriver/issues/2892#issuecomment-1602452632

fix(2892): normalize the type of SCM user id to String

---

models/stage.js

Sometimes we might need to update stage `archived` field.
This PR allows updating stage `archived`.
Related to https://github.com/screwdriver-cd/data-schema/pull/510

fix(2767): Allow update stage archived [1.5]

---

migrations/20230720-update_branch_name_length.js
models/pipeline.js

Currently, scmUri is set to 128 characters, so if a branch name or a src directory is very long, the 128 characters will be exceeded and the pipeline will not run and an error will occur.
A pipeline runs successfully even if a branch name or src directory is long.
The configuration of scmUri is `<scm name>:<Repository ID>:<Branch name>:<src dir path>`.
A branch name limit is 250 characters.
A src dir path limit is 100 characters. ([link](https://github.com/screwdriver-cd/data-schema/blob/f2e6b3b29145866ad1aff038986cae80577dac30/core/scm.js#L36))
Also, to avoid problems when the scm is slightly longer, set it to 500 characters.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority …

fix: expand scmUri length

---

migrations/20221003-add_column_setup_teardown_startFrom_to_stage.js
migrations/20230810151625-drop_and_recreate_stages.js
test/helper.js
test/models/index.test.js

DB migration script added in PR https://github.com/screwdriver-cd/data-schema/pull/510 resulted in unexpected changes.
Script intended to do below changes
1. remove column `groupEventId`
2. add new columns `setup`, `teardown` and `archived`
3. remove unique constraint involving `groupEventId` (`name`, `pipelineId` and `groupEventId`)
4. add unique constraint on just `name` and `pipelineId`
There were below of issues
- Step#1 was not associated with the transaction
- Step#3 failed since the constraint was already removed when column `groupEventId` was removed. 
```
ERROR: Unknown constraint error
```
- Transaction was rolled back. But, it didn't add back `groupEventId` as it was not associated with the transaction. 
- Error was caught by `catch` block and did nothing. Since the error …

fix(2767): Drop and recreate stages table

---

migrations/20230822154332-update-templateTags-unique-constriant.js

PR https://github.com/screwdriver-cd/screwdriver/issues/2135 added a new column `templateType` to `templateTags` table.
With this, we intend to store tags for pipeline level templates in `templateTags` (where we currently store job level template tags) and distinguish job level and pipeline level template base on `templateType`.
But the unique constraint was not updated to include `templateType`.
Include `templateType` in the unique constraint.
https://github.com/screwdriver-cd/screwdriver/issues/2135

fix(2135): Update unique constraint for templateTags

---

config/compatibilities.js
models/command.js
models/template.js
test/data/command.yaml
test/data/template.yaml

Add cloud readiness on template level, supported `clouds` field is optional

feat: add cloud readiness for template

---

models/pipeline.js

Pipeline model is a little complex, we have CREATE_MODEL, UPDATE_MODEL, and the previous PR https://github.com/screwdriver-cd/data-schema/pull/533/ forgot to include `badges` definition to `UPDATE_MODEL`
This PR fixes that, when API calls `PUT`, with `badges: {}` in the payload, payload will pass the hapi validate 

fix: add badges to UPDATE_MODEL of pipeline

---

config/template.js
plugins/executor.js
test/data/executor.start.yaml

Sometimes pods need more information.
This PR adds template info and prNum to executor start config.
NA

fix: Add template info and prNum to executor start [0]

---

plugins/executor.js

configPipelineId does not always exist
This PR makes configPipelineId optional for executor start.
Related to https://github.com/screwdriver-cd/data-schema/pull/536/files#diff-a1eeedbd9535815be45f09a81926ba437ac5e131adbc27069dba042dc9262cdeR23

fix: pipeline schema for executor start

---

plugins/executor.js

Pipelines do not always have template.
Make new fields optional.
Related to https://github.com/screwdriver-cd/data-schema/pull/536

fix: Make new executor start fields optional

---

config/regex.js
models/job.js
test/config/regex.test.js

Regex associated with `job` name is strict and does not allow setup and teardown jobs created by the backend for a stage which follows the pattern like `stage@<STAGE_NAME>:setup` or `stage@<STAGE_NAME>:teardown`
Ex: `stage@production:setup`
This results in below issues:
1. Validator fails to permit the pipeline configuration which has one or more stages defined
2. Validation of the API response for the endpoint `/v4/pipelines/<PIPELINE_ID>/jobs` fails when stage setup/teardown jobs exist. 
Relaxing the job name Regex to allow stage setup/teardown jobs
https://github.com/screwdriver-cd/screwdriver/issues/2767
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make …

fix(2767): Relax job name Regex to allow stage setup/teardown jobs

---

models/pipeline.js
test/data/pipeline.yaml

Add `defaultName` and `defaultUri` to `badge` object to accommodate populating default values and allow user override.
https://github.com/screwdriver-cd/coverage-sonar/pull/73

fix: add defaultName and defaultUri for sonar system auto population [1]

---

migrations/20231106181001-add-template-and-date-index-to-builds.js
migrations/20231106181001-add-templateId-and-createTime-index-to-builds.js
models/build.js
test/models/build.test.js

https://github.com/screwdriver-cd/screwdriver/issues/2862#issuecomment-1786509652
Update the index to include `createTime`
https://github.com/screwdriver-cd/screwdriver/issues/2862

fix(2862): Filter 'builds' by templates and creation time performance degrade

---

config/regex.js
test/config/regex.test.js

On GitHub, it was possible to use full-width space of Japanese in branch names, but these characters were not available in SD.
Allows pipelines to be created and built with branch names that contain special characters and full-width space of Japanese.
For example, the following branch names are available.
```
a!"#$%&'()-=|@`{;+]},<.>/　a
```
The following two PRs are associated with this PR.
- https://github.com/screwdriver-cd/scm-github/pull/218
- https://github.com/screwdriver-cd/ui/pull/963

fix: Make special characters available in branch names

---

config/regex.js
test/config/regex.test.js

If I try to create a pipeline with a colon in the rootDirectory, I get a validation error.
I fixe so that validation errors do not occur even when a colon is included.
issue: https://github.com/screwdriver-cd/screwdriver/issues/2952
PR:
https://github.com/screwdriver-cd/scm-github/pull/220
https://github.com/screwdriver-cd/scm-base/pull/96
https://github.com/screwdriver-cd/launcher/pull/469

fix(2952): Allow colon to be used in root directory

---

models/stage.js
test/data/stage.yaml

Stage get is failing at setup/teardown schema validation.
This PR changes setup/teardown for stage to number. We can change to array in the future if we feel it is needed.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2767

fix(2767): Stage setup and teardown should be number

---

models/stage.js
test/models/stage.test.js

`setup` and `teardown` should always exist for a stage.
A stage must have at least one job.
Update model and DB schema
- `setup` and `teardown` are non nullable
- `jobIds` should not be empty
https://github.com/screwdriver-cd/screwdriver/issues/276

fix(2767): Stage must always have valid setup and teardown job IDs

---

migrations/20240122194105-stage_setup_teardown_required.js

Related to https://github.com/screwdriver-cd/data-schema/pull/547
Forgot to attach the migration file.
Include the migration script to align with the schema
**Before (MySQL)**
**After (MySQL)**
https://github.com/screwdriver-cd/screwdriver/pull/276

fix(2767): Stage must always have valid setup and teardown job IDs - migration script

---

config/annotations.js

`setup` / `teardown` job for a `stage` are implicitly created if it is not configured in the `screwdriver.yaml`.
We need a mechanism to identify these implicitly created `setup` / `teardown` jobs to take necessary actions.
Ex: skip execution, hide it from workflow graph in the UI, etc
This PR adds a new annotation to job annotations: `screwdriver.cd/virtual`.
https://github.com/screwdriver-cd/screwdriver/issues/3022

feat(3022): Add annotation to mark implicitly created stage setup/teardown jobs are virtual

---

config/annotations.js

Job annotation `screwdriver.cd/virtualTrigger` was introduced in https://github.com/screwdriver-cd/data-schema/pull/552.
We need to rename it to `screwdriver.cd/virtualJob`
Remove job annotation `screwdriver.cd/virtualTrigger`.
Add job annotation `screwdriver.cd/virtualJob`
https://github.com/screwdriver-cd/screwdriver/issues/3022

fix(3022): Rename 'screwdriver.cd/virtualTrigger' job annotation to ' screwdriver.cd/virtualJob'

---

api/validator.js
test/data/validator.output.yaml

api throws 500 error when validating yaml with pipeline template
add templateVersionId to validator output

fix: add templateVersionId to validator output

---

migrations/20240306-remove_column_commit_from_build.js
models/build.js
test/data/build.yaml

https://github.com/screwdriver-cd/data-schema/pull/555 breaks `GET /v4/builds/{id}` because api still try to return `commit`
remove `commit` column since it was obsolete in current implementation, commit information was stored in `meta` and `commit` was not being used

fix: remove commit column from build

---

config/workflowGraph.js
test/data/config.workflowGraph.yaml

Workflow graph node (Ex: implicit setup/teardown job of a stage) for an event is identified as virtual based on the presence/value of `screwdriver.cd/virtualJob` annotation in the corresponding job definition.
Since the job definition reflects the latest configuration from `screwdriver.yaml`, referring to current annotations of the job may not be reliable to identify it as virtual for an event.
We need a way to preserve whether the job is virtual or not when event is created.
Add a new attribute `virtual` in the workflow graph `node` to indicate whether it is virtual or not.
https://github.com/screwdriver-cd/screwdriver/issues/3022
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the …

feat(3022): Mark workflow node as virtual if it corresponds to a virtual job

---

models/event.js

A client can add parameters as payload in the meta field when creating an event via `/v4/events` POST API. But the API documentation use `{}` empty object as the default `meta` payload. 
Provide a concise example for clients to send parameters payload when creating an event through API. 

feat: add example to use parameters for event model

---

plugins/datastore.js

Currently a lot of calls are being made on the PR tab page in the UI to: 
- `GET /pipelines/:id/events?count=1&page=1&prNum=prNum`
- `GET /jobs/:id/builds?count=10&page=1`
- `GET /events/:id/builds`
It would be nice if we could simplify these calls to get only latest builds in a PR and make fewer calls to the API.
This PR adds `inverse` field to datastore search.
Related to https://github.com/screwdriver-cd/screwdriver/pull/3078, https://github.com/screwdriver-cd/datastore-sequelize/pull/93
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

fix: Add new inverse field to datastore search

---

config/pipelineTemplate.js
test/data/config.pipelineTemplate.yaml

Would be nice if users could add stages to pipeline template.
This PR allows `stages` field in pipeline template.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3103

fix(3103): Allow stages in pipeline template

---

config/base.js
test/data/config.base.pipelineTemplate.yaml

Would be nice if users could config stages in pipeline template.
This PR also relaxes schema for pipeline template in config-parser. Previous PR missed similar schema
Related to https://github.com/screwdriver-cd/data-schema/pull/560, https://github.com/screwdriver-cd/data-schema/pull/563, https://github.com/screwdriver-cd/screwdriver/issues/3103

fix(3103): Add stages to config-parser schema for pipeline template

---

config/regex.js
test/config/regex.test.js

As the current implementation, join case is not supported for a trigger caused by stage. See below.
Relax the regex to support join case for a stage trigger. 
https://github.com/screwdriver-cd/screwdriver/issues/3066

feat(3066): relax the stage trigger to allow join

---

config/base.js
test/config/base.test.js
test/data/config.base.pipelineTemplate-customized.yaml
test/data/config.base.pipelineTemplate.yaml

It would be nice if users could customize the image, settings, environment, and requires within the job configuration of pipelines that are using a template.
This PR allows `requires` in shared settings for pipeline template yaml.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3106

fix(3106): Allow shared.requires for pipeline template yaml

---

config/base.js
test/data/config.base.pipelineTemplate-customized.yaml

At present, users utilizing a pipeline template are restricted from making any modifications within the job configuration.
This PR allows users to customize image, settings, environment, and requires within `job` field when using pipeline template.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3106

fix(3106): Allow user to customize job when using pipeline template

---

config/regex.js
models/event.js
test/models/event.test.js
test/models/templatetag.test.js

`startFrom` of `event` model current allows below patterns
- SCM events. Ex: `~commit`, `~tag`
- internal job names. Ex: `component`, `stage@integration:setup`
- external job triggers. Ex: `~sd@123:release`
Relax the schema to allow an event to start from a `stage`.
Ex: `stage@integration`
https://github.com/screwdriver-cd/screwdriver/issues/3112

feat(3112): Add support to start an event from a stage

---

plugins/scm.js
test/data/scm.addPrCommentWithScmRepo.yaml
test/data/scm.addWebhookWithScmRepo.yaml
test/data/scm.decorateCommitWithScmRepo.yaml
test/data/scm.getBranchListWithScmRepo.yaml
test/data/scm.getChangedFilesInputWithScmRepo.yaml
test/data/scm.updateCommitStatusWithScmRepo.yaml
test/plugins/scm.test.js

I would like to skip GitHub access if `scmRepo` is available. But some methods in the scm plugin do not allow to pass `scmRepo` argument.
https://github.com/screwdriver-cd/screwdriver/issues/3146
Allow to pass `scmRepo` argument into methods that using `lookupScmUri` method inside.
https://github.com/screwdriver-cd/screwdriver/issues/3146

feat(3146): Allow to pass scmRepo argument to scm plugins methods [1]

---

config/pipelineTemplate.js
test/data/pipelineTemplateVersions.get.allFields.yaml

Would be nice if we could see workflowGraph when we get pipeline template versions in pipeline template page.
This PR adds workflowGraph to pipeline template config schema.
NA

fix: Allow workflowGraph for pipeline template versions model

---

config/regex.js
test/config/regex.test.js

Didn't have a the regex for checking for a stage setup job in a central place
Adds the regex for checking if a job is a stage setup
https://github.com/screwdriver-cd/screwdriver/issues/3143

feat(3143): Add regex and tests for a stage setup job

---

config/regex.js
test/config/regex.test.js

No regex exists to check if a job is one of stage setup or teardown
Add regex to check if a job is a stage setup or teardown
https://github.com/screwdriver-cd/screwdriver/issues/3143

feat(3143): Add regex for stage setup or teardown job names

---

config/pipelineTemplate.js
migrations/20220607152947-add_column_state_to_pipeline.js
models/pipelineTemplateVersions.js
test/data/pipelineTemplateVersions.get.allFields.yaml
test/data/pipelineTemplateVersions.yaml

Changes were made in https://github.com/screwdriver-cd/data-schema/pull/571 to store `workflowGraph` of pipeline template as part of the `config` 
Move `workflowGraph` out of `config` and keep it at the same level as `config`
https://github.com/screwdriver-cd/screwdriver/issues/3171

feat(3171): Persist pipeline template workflowGraph in a new column (BREAKING CHANGE)

---

config/pipelineTemplate.js
migrations/20240827173654-add-workflowgraph-to-pipelineTemplateVersions.js
models/pipelineTemplateVersions.js
package.json
test/data/pipelineTemplateVersions.get.allFields.yaml
test/data/pipelineTemplateVersions.yaml

BREAKING CHANGE: Move workflowGraph out of config and keep it at the same level as config
Changes were made in https://github.com/screwdriver-cd/data-schema/pull/571 to store `workflowGraph` of pipeline template as part of the `config` 
Move `workflowGraph` out of `config` and keep it at the same level as `config`
https://github.com/screwdriver-cd/screwdriver/issues/3171

feat(3171): Persist pipeline template workflowGraph in a new column

---

migrations/20240906-add-templateId-and-archive-index-to-builds.js
models/job.js
test/models/job.test.js

related https://github.com/screwdriver-cd/screwdriver/issues/3191
https://github.com/screwdriver-cd/models/pull/612 added archived to the job table filter in the job template metrics.
However, since the only index in the job table is `templateId`, the index does not work effectively and the job template details page takes a long time to load.
Create an index for`templateId` and `archived` to speed up the loading of template detail pages
https://github.com/screwdriver-cd/screwdriver/issues/3191

Add templateId and archived index to jobs table

---

migrations/20241014165446-add-status-message-type-to-build.js
models/build.js
test/data/build.update.yaml
test/models/build.test.js

All the build status message are currently treated/visualized as warning in the UI. We need a mechanism to distinguish the messages based on severity
Add a new field `statusMessageType` to the `build` with `ERROR`, `WARN` and `INFO` as the allowed values
https://github.com/screwdriver-cd/screwdriver/issues/3211

feat(3211): Add a new field to builds to indicate the severity of the status message

---

migrations/20250113235218-add-scope-and-scopeId-to-banner.js
models/banner.js
package.json
test/data/banner.create.invalid.yaml
test/data/banner.create.yaml
test/data/banner.get.yaml
test/data/banner.list.yaml
test/data/banner.update.invalid.yaml
test/data/banner.update.yaml
test/data/banner.yaml
test/models/banner.test.js

The current implementation of banner schema is at the global level. 
Sometimes banner is needed at the pipeline or build level only. 
https://github.com/screwdriver-cd/screwdriver/issues/3266

feat(3266): add scope and scopeId to banner models

---

config/annotations.js

Build Cluster annotation on a job is currently only derived from pipeline or from screwdriver config.
Screwdriver Admin should have a way to override the behavior to move jobs to some cluster
This PR adds a new annotation to support Screwdriver admin level override for build cluster

feat: add new admin annotation to update job build cluster

---

config/base.js

I am now modifying it so that sourcePaths can be used in stage.
- https://github.com/screwdriver-cd/data-schema/pull/591
- https://github.com/screwdriver-cd/config-parser/pull/178
Disable setting sourcePaths for stage teardown jobs.
https://github.com/screwdriver-cd/screwdriver/issues/3271

fix(3271): Disable setting sourcePaths for a stage teardown job

---

config/regex.js
test/config/regex.test.js

The regex `^~?sd@(\d+):(?:([\w-]+)|(stage@([\w-]+):setup))$` does not consistently return the matching group to get the job name 
Fix the regex to consistently retrieve the job name as the second group.
https://github.com/screwdriver-cd/screwdriver/issues/3310

fix(3310): Consistently extract external job name

---

migrations/20250318145743-add-pipelineId-and-archived-index-to-jobs.js
models/job.js

Queries to find jobs in the pipeline with large numbers of archived jobs can be slow.
Location of the call where the slow query was actually detected.
https://github.com/screwdriver-cd/models/blob/3c515d63a2d7e52a25684e2ae93b552e204c90c2/lib/pipeline.js#L1456
Add pipelineId and archived index to job table.

fix: Add pipelineId and archived index to jobs

---

models/pipeline.js

If screwdriver using mysql 5.X, default value cannot be set in TEXT field.
Because of that, old pipelines have null adminUserIds column.
Relax pipeline adminUserIds restriction for mysql backward compatibility.
- remove required restriction for null value.
- move adminUserIds from requiredFileds to optionalFields.
https://github.com/screwdriver-cd/screwdriver/pull/3325

fix: Relax pipeline adminUserIds restriction

---

migrations/20250425162418-add-status-to-event.js
models/event.js
test/data/event.get.full.yaml
test/data/event.get.pr.yaml
test/data/event.get.yaml
test/data/event.yaml
test/models/event.test.js

Overall execution status of the event is being determined by UI based on individual build statuses.
We need to determine the status in the backend and persist in DB.
Add a new column `status` to `events` table
https://github.com/screwdriver-cd/screwdriver/issues/3328

feat(3328): Add status column to events table

---

migrations/20250513162834-update-status-length-in-event.js
models/event.js

PR https://github.com/screwdriver-cd/data-schema/pull/599 added a new column `status` (Max length = 10) column to `events` table.
There are statuses (Ex: `IN_PROGRESS`) exceeding the declared max length. 
Increase the max length to 15.
https://github.com/screwdriver-cd/screwdriver/issues/3328

feat(3328): Increase the size of status column value in events table

---

api/loglines.js

Allows timestamps to be added to downloaded logs.
This PR by itself does not affect the existing behavior.
The releated PR
- https://github.com/screwdriver-cd/screwdriver/pull/3365
- https://github.com/screwdriver-cd/ui/pull/1436
Allows user to select.
- Whether to include a timestamp 
- Timestamp format 
- Timestamp time zone (Only affects full-time and simple-time format)
About Timestamp format
- full-time: iso 8601 format
- simple-time: hh:mm:ss format like UI
- elapsed-build: hh:mm:ss format like UI
- elapsed-step: hh:mm:ss format like UI
https://github.com/screwdriver-cd/screwdriver/issues/2856
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …

feat(2856): Add timestamp in downloaded logs [1]

---

migrations/20250912140626-remove-pipelineId-and-createTime-index-from-events.js

The `removeIndex` signature is of the following format:
```javascript
public async removeIndex(tableName: string, indexNameOrAttributes: string | string[], options: object): Promise
```
https://sequelize.org/api/v6/class/src/dialects/abstract/query-interface.js~queryinterface#instance-method-removeIndex
The current migration fails due to the following error:
```
ERROR: TypeError: indexNameOrAttributes.join is not a function
``` 
Fixes the `removeIndex` migration to use the expected function signature
#608

fix: Adhere to removeIndex signature
